### ISSUE TITLE
Json Options without custom controller.

### ISSUE THREAD

**Issue by dhruv217** [EntityGraphQL/EntityGraphQL#101]
Is there any way to configure JsonOptions for System.Text.Json in schema.AddGraphQlSchema method if a custom controller is not used to build the 'graphql' endpoint..?

**Comment by lukemurray** [comment]
Great point! Not yet. Will add it. Assume you just want to be able to pass the `JsonSerializerOptions` to it?

**Comment by dhruv217** [comment]
Yes that should be enough. Also, I was wondering since dotnet 6.0 we can add global json option with `builder.Services.Configure<JsonOptions>`

any way that could be utilized to configure `JsonSerializerOptions `instead of passing them into `MapGraphQL` ..?

**Comment by lukemurray** [comment]
1.3.0 will allow you to register services to override the JSON options used. But this is for de/serialisation you might also be looking for the `fieldNamer` func when creating the schema. Hoping the updated docs (not yet published but here - https://github.com/EntityGraphQL/EntityGraphQL/blob/master/docs/content/serialization-naming.md) help
