### ISSUE TITLE
Add support for GraphQL Union Types

### ISSUE THREAD

**Issue by lukemurray** [EntityGraphQL/EntityGraphQL#107]
https://graphql.org/learn/schema/#interfaces

At least this one I personally have hit times where they would be useful :)

**Comment by lukemurray** [comment]
Actually I want Union Input types.. which may come in a future spec in the form of oneOf https://github.com/graphql/graphql-spec/pull/825

**Comment by lukemurray** [comment]
#177 adds support for this

**Comment by Bosch-Eli-Black** [comment]
Oooh, looks like this _just_ missed the 3.0.5 release, haha.

Looking forward to using this in the next release! 🙂

**Comment by lukemurray** [comment]
Yep, has breaking changes. there will be a 4.0.0-beta1 soonish see the milestone https://github.com/EntityGraphQL/EntityGraphQL/milestone/2

**Comment by Bosch-Eli-Black** [comment]
Oh, cool, thanks! 🙂
