### ISSUE TITLE
Issue deserialising sort params from variables - Update docs for working with Newtonsoft.Json

### ISSUE THREAD

**Issue by bzbetty** [EntityGraphQL/EntityGraphQL#125]
Currently getting this error when I'm trying to pass sort params as variables, trying to figure out if my input is actually deformed or if it's a bug.

"Supplied variable 'sort' can not be applied to defined variable type '[PeopleSortInput]'"

I've modified SortTests.TestAttribute to replicate the issue by replacing the building of the QueryRequest with this

```
       var body = @$"{{
                    'query': 'query people($sort: [PeopleSortInput]) {{ people(sort: $sort) {{ lastName }}  }}',
                    'variables': {{ sort: [{{'lastName': 'DESC'}}] }},                
                    'operationName':'people'
                }}";
            var gql = JsonConvert.DeserializeObject<QueryRequest>(body);
```

if I then add in the following line it works again, so definitely seems like something wrong with how i'm passing in the sort

```
gql.Variables = new QueryVariables{
  {"sort", new [] { new {lastName = "DESC" } } }
};
```

**Comment by bzbetty** [comment]
catching an exception in BuildDocumentVariables

{"Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'System.Collections.Generic.IDictionary`2[System.String,System.Object]'."}

**Comment by bzbetty** [comment]
switching from Newtonsoft to JsonSerializer seems to fix it

```

         var jsonOptions = new JsonSerializerOptions
            {
                // the internal generated types use fields so include this
                IncludeFields = true,
                PropertyNamingPolicy = JsonNamingPolicy.CamelCase, // match common JSON style and fits with many GraphQL tools
            };
            // Convert ENUMs to their string names
            jsonOptions.Converters.Add(new JsonStringEnumConverter());

            var body = @$"{{
                    ""query"": ""query people($sort: [PeopleSortInput]) {{ people(sort: $sort) {{ lastName }}  }}"",
                    ""variables"": {{ ""sort"": [{{""lastName"": ""DESC""}}] }},                
                    ""operationName"":""people""
                }}";
            var gql = JsonSerializer.Deserialize<QueryRequest>(body, jsonOptions);
```

**Comment by lukemurray** [comment]
Sorry, I need to update the docs (I thought I had).

EntityGraphQL doesn't know anything about Newtonsoft.Json types and `JsonConvert.DeserializeObject<QueryRequest>(body);` ends up creating a dictionary for the variables that have `JObject` and/or `JToken` etc.

You need to add a custom converter.

You can follow the example in the [test](https://github.com/EntityGraphQL/EntityGraphQL/blob/master/src/tests/EntityGraphQL.Tests/SerializationTests.cs#L25).

I'll leave this open as a reminder to update the docs!
