### ISSUE TITLE
Schema output has mixed line endings

### ISSUE THREAD

**Issue by breyed** [EntityGraphQL/EntityGraphQL#137]
The string returned by `SchemaProvider<T>.ToGraphQLSchemaString` contains a mix of CRLF and LF line endings. When saved to a file, this causes Visual Studio to prompt to normalize the line endings when you open the file. Anything consistent would be a nice improvement.

**Comment by lukemurray** [comment]
Are you on windows? On a Mac with VS Code I have not had issue. But looking at it it might be happening because of the mix of StringBuilder and inline @"" strings
