### ISSUE TITLE
How to offer query fields whose CLR types share the same name (although in different namespaces)

### ISSUE THREAD

**Issue by breyed** [EntityGraphQL/EntityGraphQL#142]
I'd like to expose through GraphQL a query some POCO classes, some of which have the same base CLR type name (although different fully qualified names) as entities that are exposed. When I create a property that returns the top-level POCO class, I get this error at startup:

> An item with the same key has already been added. Key: ThePocoTypeName

This happens even if I use `RemoveTypeAndAllFields` on the entity type. I'm fine with the GraphQL type names differing from the CLR type names. How can avoid the duplicate key error?

**Comment by lukemurray** [comment]
Any chance you can share some code to help me follow along? Even better if it is a unit test :)

**Comment by breyed** [comment]
This gives the idea:

``` c#
class E {
    public int Id { get; set; }
}

namespace N {
   class E {
      public string Name { get; set; }
   }
}

class GraphQLDBContext: DBContext {
     public DBSet<E> Es { get; set }
     public N.E NonEFProperty => new N.E();
}
```

The problem seemed to boil down to GraphQL's namespace not allowing for multiple types with the same name. It's possible that there is a way to rename the GraphQL type name of one of the conflicting CLR types. I ended up changing the design to avoid the conflict, and so didn't explore further the API after I posted this.

I'm going to close this issue, since it's not important to me any longer, and there may even be an existing solution that I'm not aware of. However, if there's not and you think type renaming would be of general interest, feel free to reopen.
