### ISSUE TITLE
Why no AddField method in schemaProvider in version 2.1.5, cannot query with argument in this version.

### ISSUE THREAD

**Issue by eureka-gh** [EntityGraphQL/EntityGraphQL#144]
Not sure, I was the only one who encounters this issue. I am using EntityGraphQL.ASPNet 2.1.5 based on the sample of https://entitygraphql.github.io/getting-started. But why I am not able to query with argument?
query
{
    properties { id name }
}
is OK,

but query
{
    properties(id: 1) { id name }
}
returns `"message": "No argument 'id' found on field 'properties'"`.

I thought `services.AddGraphQLSchema<DemoDbContext>();` should somehow add arguments automatically according to the `DbSet<Property> properties` attributes.

I noticed I can add Field with `ArgumentHelper`
```
var schema = new SchemaProvider<DemoContext>();
schema.AddType<Property>("Property", "Information about a Property);

// add our root-level query field with an argument
schema.AddField(
    "Property",
    new {
        id = ArgumentHelper.Required<int>()
    },
    (ctx, args) => ctx.People.FirstOrDefault(p => p.Id == args.id),
    "Fetch Property by ID"
);
```
But no AddField available to call in version 2.1.5. Does this version somehow hide this method in flavor of other approaches, unfortunately, I didn't see an example in the doc https://entitygraphql.github.io/.

**Comment by lukemurray** [comment]
To clean up the API this was moved.

GraphQL has `Query` base type. To add to that you use

```
schema.Query().AddField()
```

And yes, by default _if_ the entity has a property named `Id` it will create a field with the `id` argument. Note that is makes the name a single (not plural) as it does not return a list. So in you example the field would be `property(id: 1)` not `properties(id: 1)`

**Comment by eureka-gh** [comment]
Hey @lukemurray, thanks for your prompt response. Before I try the `schema.Query().AddField()` approach. Please allow me to follow up the "cannot query with argument in this version" issue. 

I suppose if I use `services.AddGraphQLSchema<DemoDbContext>();`, the EntityGraphyQL library will leverage reflection to build schema and create Fields automatically. I don't need to create a `SchemaProvider` and call `Query().AddField` to explicitly add argument(s) for some properties. E.g. I have `Dbset<Student> students` in my `DbDemonContext`, and one of properties of Student is SurName. I should be able to call
```
query {
    students {
        id
        firstName
        surName
    }
}
```
to get all students (that's works for me)
and call
```
query {
    student(surName: "Alice") {
       id
       firstName
       address   
    }
}
```
here, use singular version to get a given student.

However, I got error
```
{
    "errors": [
        {
            "message": "Field 'student' not found on type 'Query'"
        }
    ]
}
```
when I use the call the second query above.

**Comment by lukemurray** [comment]
OK. The auto schema creation only adds a "single" field with an argument of `id` if it finds a property named `Id`. It makes an assumption that Id is unique. and that query is valid. For all other properties, e.g. `SurName` it does not do anything as it doesn't know enough about the model to make assumptions.

e.g. 
```c#
public class Db : DbContext {
   public DbSet<Student> Students { get; set; }
}

public class Student {
  public int Id { get; set; }
  public string SurName { get; set; }
}
```

This will create a graphic schema like

```gql
schema {
    query: Query
}

type Query {
    students: [Student]
    student(id: Int!): Student
}

type Student {
    id: Int!
   surName: String
}
```

So the valid fields at the top level are only - example query

```gql
query {
  students { id name }
  student(id: 1) { id name }
}
```

If you want more you need to extend the schema.

```c#
// assuming you want multiple results for surName search
services.AddGraphQLSchema<DemoDbContext>(schema => {
    schema.Query().ReplaceField("students", new { surName = (string)null }, (db, args) => db.Students.WhereWhen(s => s.SurName.Contains(args.surName), !string.IsNullOrEmpty(args.surName), "List of students optionally filtered by surname");
});
```

I hope this helps.

**Comment by eureka-gh** [comment]
Hey @lukemurray, thanks for the explanation. It makes more sense to me now. The schema.Query().ReplaceField works for me to replace the default filtering from id to surName. It looks to me the singular or plural doesn't matter, I can use
```
query {
    students(surName: "") {
       id
       firstName
       surName
    }
}
```
to filter some entities. I think in term of the querying issue, I will mark it close.

However, it will be very helpful, if you can hint me how I can add multiple filters for a querying.
Suppose, the Student class has more properties like age, height, address. How I can add multiple filters(e.g. age > 18 and address in WA) for those properties? The ReplaceFlied method seems to me that it only adds one filter for a class/field. Hope my question makes sense to you.

**Comment by lukemurray** [comment]
Sure

```
services.AddGraphQLSchema<DemoDbContext>(schema => {
    schema.Query().ReplaceField("students", new { surName = (string)null }, (db, args) => db.Students.WhereWhen(s => s.SurName.Contains(args.surName), !string.IsNullOrEmpty(args.surName), "List of students optionally filtered by surname");
});
```

All this does is create a field - you can name it what ever you want. Here is is named "students" because it will return an array/list of results.

https://entitygraphql.github.io/schema-creation/02-fields this will show you how to build multiple arguments. You just build any LINQ expression you need to to your logic.

For example

```
services.AddGraphQLSchema<DemoDbContext>(schema => {
    schema.Query().ReplaceField(
        "students",  // name of the field in the schema
        new { // arguments
           surName = (string)null,
           address = (string)null,
           age = (int?)null,
           // any more
        }, 
       // you can use LINQ methods to build your query for this field.
       (db, args) => db.Students
           .WhereWhen(s => s.SurName.Contains(args.surName), !string.IsNullOrEmpty(args.surName))
           .WhereWhen(s => s.Address.Contains(args.surName), !string.IsNullOrEmpty(args.address)) 
           .WhereWhen(s => s.Age >= args.age), args.age.HasValue), 
       "List of students" // description of the field
    );
});
```

**Comment by eureka-gh** [comment]
That really helps me a lot. Thanks @lukemurray. I will mark it closed.
