### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by breyed** [EntityGraphQL/EntityGraphQL#147]
The prompt addressing of issues and corresponding releases of EntityGraphQL is wonderful, but it would be even more helpful if future releases would use [Semantic Versioning](https://semver.org/) to provide a heads up that a release involves breaking changes.

In 2.2.0 `SchemaBuilder.GetFieldsFromObject` added an `autoCreateIdArguments`. The additional is a good one and easy enough to update the code for. I just didn't expect the incompatible API change.

**Comment by bzbetty** [comment]
That's my bad. Luke did warn me about breaking changes. Sometimes it's hard to realise which are internal APIs and external ones.

**Comment by lukemurray** [comment]
Yes this was an oversight. 2.2.0 was not meant to introduce breaking changes!

I would not really expect typical use to include `SchemaBuilder.GetFieldsFromObject`. Can I ask how you are using it?

**Comment by breyed** [comment]
We have an existing data model designed for a mobile app that we are reusing for the web app. That data model is a view model that is fairly different in structure from the database structure. We're exposing it alongside the ordinary GraphQL queries against the database.

Several of the fields in the mobile data model aren't applicable for the web, but most of them are desirable. To filter, we have a helper method that adds a type with all its fields except for those specified. Altogether it looks like this:

``` c#

public static void ConfigureSchema(SchemaProvider<GraphQLContext> schema) {
	void AddType<T>(params string[] exceptFields) {
		var fields = SchemaBuilder.GetFieldsFromObject(typeof(T), schema, createEnumTypes: true, autoCreateIdArguments: false, schema.SchemaFieldNamer, createNewComplexTypes: false, isInputType: false)
			.ExceptBy(exceptFields, f => f.Name);
		schema.AddType<T>(typeof(T).Name, null).AddFields(fields);
	}

	AddType<Type1>("excludedField1", "excludedField2");
	AddType<Type2>(); // No excluded fields.
}
```

However, I wrote that before looking at the code and trying to track down missing type errors. It turns out that this version of the AddType helper is nearly identical and is simpler:

``` c#
void AddType<T>(params string[] exceptFields) {
	var type = schema.AddType<T>(typeof(T).Name, null).AddAllFields();
	foreach (var field in exceptFields)
			type.RemoveField(field);
}
```

The only difference is a field added with `AddField` went from appearing at the bottom of its type to the top in the `ToGraphQLSchemaString` output. To minimize churn when diffing the .graphql file, it is best if the field order was the same for either approach.

**Comment by lukemurray** [comment]
> it is best if the field order was the same for either approach.

Good idea too!

Interesting use case and yes I think I was use the second way, I wasn't expecting people to be using `SchemaBuilder.GetFieldsFromObject` :) 

Also 2.3.0 is being prepared and I do not aim to make breaking changes either (they'll come in 3.0.0). Please let me know if you happen to see any. I'll be reviewing the changes again before it is ready.

**Comment by breyed** [comment]
No. Definitely not worth an extra release, since the "breakage" was so minor. Going forward, I just being aware of incompatible changes to public methods, and bumping the major version number when they happen, is fine for a project this time. Keeping it simple leaves more time for working on amazing features! :-)
