### ISSUE TITLE
Show dependent of missing type in error

### ISSUE THREAD

**Issue by breyed** [EntityGraphQL/EntityGraphQL#148]
When the schema provider cannot find  a type, it reports an error like this:

> No schema type found for dotnet type _TypeName_. Make sure you add it or add a type mapping

It would be helpful for the error message to display the type and field that referenced the missing type.

An a minor detail on the same error: The second sentence in the error message could use a period at the end.

**Comment by lukemurray** [comment]
Good idea. We don't always have that context though (e.g. you can just ask the provider for a type). But when we do we should show it. Certainly help find the types not set up.
