### ISSUE TITLE
Threading model

### ISSUE THREAD

**Issue by breyed** [EntityGraphQL/EntityGraphQL#162]
The threading model for EntityGraphQL should be determined and documented. In principal, EntityGraphQL could be multi-threaded. [Per the GraphQL docs](https://graphql.org/learn/queries/#multiple-fields-in-mutations):

> While query fields are executed in parallel, mutation fields run in series, one after the other.

A separate thread could run for each query. However, the overhead and complexity of multiple threads seems unlikely to be worthwhile compared to the alternative of a single thread that takes advantage of async calls to fetch data.

Whatever is decided should be documented so that users have a guarantee to work from. It seems to be that the best approach is a single thread per request. That way, database contexts can be scoped services (which is typical). Similarly, queries and mutations that make calls to external web services can safely use the [single-threaded HttpContext accessor](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?) to access [HttpContext.RequestAborted](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.requestaborted) to cancel the dependent request if the GraphQL request is aborted.

**Comment by lukemurray** [comment]
I agree with your last paragraph regarding the points of the scoped db contexts.

And this is what happens today. unless I'm miss understanding something. So this would be just documenting that fact clearly?

**Comment by breyed** [comment]
I wasn't sure if EntityGraphQL used threads to run queries in parallel. My guess was no, but I thought I'd check. Thanks for confirming that per request, it only uses one thread at a time. So yes, the only thing to do is just to document this guarantee somewhere.

**Comment by breyed** [comment]
Thanks for writing up the initial docs. You provided a good foundation that I was able to build the clarification in #179 from.
