### ISSUE TITLE
ResolveWithService replaces parameter that is an expression

### ISSUE THREAD

**Issue by Ko-Lin** [EntityGraphQL/EntityGraphQL#170]
```
schema.Type<Project>().AddField("someService", "Get project configs if they exists")
                .ResolveWithService<ConfigService>((p, srv) => srv.Get(p.Name, p.Children.FirstOrDefault().Name));
```
expression `p.Children.FirstOrDefault().Name` is not resolved and was provided with the same value as `p.Name` to the service call of `.Get(...)`

see test cases created here:
https://github.com/Ko-Lin/EntityGraphQL/commit/0f8e16934124c775835eb8afa1ba8117ef18d440

**Comment by lukemurray** [comment]
OK digging into this more. It is related to the fact that we are traversing a relation on the entity.

As the docs say with the service limitations

>Do not traverse through a relation in your field expression that uses ResolveWithService()

I still have a few ideas on how to fix it but I don't think it'll be something that will make it into the next release.

**Comment by Ko-Lin** [comment]
Ok, fair enough. Thanks for pointing it out. I will kept this in mind going forward.
