### ISSUE TITLE
Filter doesn't support multiple enums in same project with same names

### ISSUE THREAD

**Issue by bzbetty** [EntityGraphQL/EntityGraphQL#173]
```
        public override Expression? VisitIdentity(EntityQLParser.IdentityContext context)
        {
            if (schema == null)
                throw new InvalidOperationException("Schema is not set");
            // this should be an enum
            var enumVal = context.GetText();
            var enumField = schema.GetEnumTypes()
                .Select(e => e.GetFields().FirstOrDefault(f => f.Name == enumVal))
                .Where(f => f != null)
                .FirstOrDefault();
            if (enumField == null)
                return null;

            var exp = Expression.Constant(Enum.Parse(enumField.ReturnType.TypeDotnet, enumField.Name));
            return exp;
        }
```

If you have 2 enums with same member names then the compiler will grab the first one that matched.

Wondering if we should support the enum name as a prefix to support this situation?

eg "person.gender == Male" becomes "person.gender == Gender.Male"

**Comment by lukemurray** [comment]
I agree. And it works for this extra language as to the graphic spec this is just a string and the impact doesn't change the return shape.

GraphQL seems to have a similar issue where (from the spec).

```
enum DogCommand {
  SIT
  DOWN
  HEEL
}
```

To reference the enum you just use `SIT` etc. So you can't have shared names in the schema. Fine when building the schema yourself as you can name the fields differently. But the SchemaBuilder will generate something invalid.
