### ISSUE TITLE
Documentation search

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [EntityGraphQL/EntityGraphQL#195]
Not sure how hard this would be to implement, but it'd be sweet if the docs (https://entitygraphql.github.io/docs) had a search function, so that I could search within the docs 🙂

**Comment by lukemurray** [comment]
FYI this will be pushed out with 4.0 in the next few weeks.

**Comment by Bosch-Eli-Black** [comment]
Sweet, thanks! 🙂
