### ISSUE TITLE
Targeting unsupported .NET runtime

### ISSUE THREAD

**Issue by breyed** [EntityGraphQL/EntityGraphQL#200]
When I open EntityGraphQL.sln, Visual Studio prompts me install:
> .NET 5.0 Runtime (out of support)

Can the project move to .NET 6.0?

**Comment by lukemurray** [comment]
Interesting. So dotnet 3.1 is still supported until the end of this year. 5 is no longer supported which means no more releases. But the library supports them all, the is the target `<TargetFrameworks>net6.0;net5.0;netstandard2.1</TargetFrameworks>`

dotnet 6 is there. netstandard 2.1 is there. I'm. not sure what that error means? Does it just mean 5.0 is out of support but it will still compile for the other targets?

**Comment by breyed** [comment]
Is there any advantage to multi-targeting EntityGraphQL.csproj and EntityGraphQL.AspNet.csproj? If no features beyond netstandard2.1 are needed, it seems that can be the sole target. For the other projects, the existing net6.0 is fine.

**Comment by breyed** [comment]
#204 will require .NET 6 (although there may be a workaround by inspecting custom attributes by hand for earlier versions, but it may not be work implementing, as most code using nullable reference types will be on .NET 6 anyway). So some conditional code may be needed. Even in that case, I think that just multitargeting netstandard2.1 and net6.0 will be sufficient - no need for net5.0.

**Comment by bzbetty** [comment]
For #204 there are helpers in the project which inspect the attributes manually to determine nullabiility that will work

**Comment by lukemurray** [comment]
`EntityGraphQL.csproj` likely doesn't need the multi target at this point. It could just target `netstandard2.1` to provide the largest support as 3.1 is still supported until the end of year.

`EntityGraphQL.AspNet.csproj` requires it as there are some big differences between ASP.NET versions and it needs to reference the right packages. Mainly `Microsoft.AspNetCore.Authorization`. You can see that [here](https://github.com/EntityGraphQL/EntityGraphQL/blob/master/src/EntityGraphQL.AspNet/EntityGraphQL.AspNet.csproj#L19)

**Comment by lukemurray** [comment]
Next breaking change release (4.0) I'll remove the 5.0 target and look at cleaning up the core project to just be netstandard2.1

**Comment by lukemurray** [comment]
I have cleaned up EntityGraphQL.sln but I want to leave EntityGraphQL.AspNet.sln as we are supporting 3.1 (valid until Dec this year) which is older so it costs nothing to support 5.0 as well and I know not everyone can move that quickly. We're still on 3.1 for a lot of things (moving soon to 6!).

When 3.1 is out of support and we have a breaking change coming in I'll remove 3.1 and 5 support.

Going to close this.
