### ISSUE TITLE
Development and production error messages

### ISSUE THREAD

**Issue by breyed** [EntityGraphQL/EntityGraphQL#205]
When a query in an added field fails, EntityGraphQL helpfully provides a GraphQL response that contains the error. However, the error message sometimes doesn't contain the message from the inner exception. For example, if Entity Framework Core is confirmed to throw on warnings in `OnConfiguring`, like this
```c#
optionsBuilder.ConfigureWarnings(b => b.Default(WarningBehavior.Throw));
```
EntityGraphQL doesn't show the actual error. For example, for a warning about client-side execution being required, the output is just:

```json
{
    "errors": [
        {
            "message": "Field 'customers' - Exception has been thrown by the target of an invocation."
        }
    ]
}
```

In development (per `IWebHostEnvironment`), the underlying cause should be shown. Conversely, for security in production, the error should show the same message that an ASP.NET Core API controller shows in production, with the exception message not provided.

**Comment by lukemurray** [comment]
What error does ASP.NET Core API controller shows in production?

**Comment by breyed** [comment]
I created a new project with:
```sh
dotnet new web
```

I changed the code to throw an exception:
```c#
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapGet("/", _ => throw new Exception("Sample error."));

app.Run();
```

I first left `ASPNETCORE_ENVIRONMENT` set to `Development` in `launchSettings.json`. In sent a GET request with the `Accept` header set to `application/json`. The HTTP response was a 500 Internal Server Error with this body:
```
System.Exception: Sample error.
   at Program.<>c.<<Main>$>b__0_0(HttpContext _) in /Users/brey/Code/Sandbox/aspnetcore/Program.cs:line 4
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: application/json
Connection: keep-alive
Host: localhost:5247
User-Agent: PostmanRuntime/7.29.0
Accept-Encoding: gzip, deflate, br
Postman-Token: a5dab21c-1b37-4224-a4fa-e7ca5e2d1a9e
```

When I changed `ASPNETCORE_ENVIRONMENT` to `Production`, the HTTP response was the same 500 Internal Server Error, but this time the response had no body (`Content-Length` was 0).

**Comment by lukemurray** [comment]
Thanks for that.

The spec talks about showing error messages to help API users. e.g. compiler errors (incorrect syntax etc). Auth error messages are often useful as well.

Would having the ability to turn off error messages work? Or maybe we can define errors that are OK and others that are not (might be hard)?

Or is it more about in dev mode include stack trace etc?

**Comment by breyed** [comment]
Errors specific to the caller's code are unlikely to expose information useful to attackers, so GraphQL compilation errors should be fine, as should anything emanating from EntityGraphQL. By contrast, unhandled exception originating in application code should be limited to development environments.

That said, there are cases where application code has error messages known to be acceptable to show in production, such as your auth example. For those cases, it would be helpful to define an `EntityGraphQLException` that the application can throw, which EntityGraphQL will catch and report out GraphQL. Exceptions of other types would be caught and logged, but not exposed to the GraphQL client. This would be a GraphQL equivalent of what a middleware library like [HTTP Exceptions](https://github.com/ofpinewood/http-exceptions) does at the HTTP request level.

**Comment by lukemurray** [comment]
I like that. There are exceptions EntityGraphQL users can throw but like need to better define which ones cause what things.Likely need to review the library use of exceptions and define some rules around them as well as having a way to tell EntityGraphQL it is in dev or prod mode.

**Comment by breyed** [comment]
One approach would be a property on `SchemaProvider`:

```c#
/// <summary>
/// Gets or sets whether to expose the <see cref="Exception.Message"/> property of exceptions thrown
/// from application code called by EntityGraphQL and caught by EntityGraphQL.
/// If false, the error message "Internal server error" will be used. If null (the default),
/// exception messages are exposed if the ASP.NET Core service `IWebHostEnvironment` service
/// is available and is set to `Developmenet`.
/// </summary>
public bool? ExposeExceptions { get; set; }

**Comment by lukemurray** [comment]
@breyed any thoughts on  the PR #262 ?

**Comment by lukemurray** [comment]
#262 introduces the ability to control this
