### ISSUE TITLE
Adding a non-nullable field

### ISSUE THREAD

**Issue by breyed** [EntityGraphQL/EntityGraphQL#209]
How do you add a non-nullable field with `SchemaType<T>.AddField`?

For example, if I do create something like this:
```c#
schema.UpdateType<Customer>(type => type.AddField("availablePurchaseOrders", null).ResolveWithService<AppDbContext>((customer, db) =>
	from purchaseOrder in db.PurchaseOrders
	where ...
	orderby ...
	select purchaseOrder));
```

the GraphQL is:
```graphql
type Customer {
	availablePurchaseOrders: [PurchaseOrder!]
}
```

The desired GraphQL is:
```graphql
type Customer {
	availablePurchaseOrders: [PurchaseOrder!]!
}
```

**Comment by lukemurray** [comment]
You should just be able to call `IsNullable(false)`

```c#
schema.UpdateType<Customer>(type => type.AddField("availablePurchaseOrders", null).ResolveWithService<AppDbContext>((customer, db) =>
	from purchaseOrder in db.PurchaseOrders
	where ...
	orderby ...
	select purchaseOrder))
IsNullable(false);
```

I had a quick look but couldn't find a way to know if nullable ref types were enabled which would allow us to switch that default logic if it was.

**Comment by breyed** [comment]
Thanks. `IsNullable` worked. I likewise couldn't find a way to detect nullability on an expression. [NullabilityInfoContext](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.nullabilityinfocontext) doesn't accept just a `Type` or `Expression`.
