### ISSUE TITLE
Can't query List<T> navigation property when not executing service fields separately

### ISSUE THREAD

**Issue by breyed** [EntityGraphQL/EntityGraphQL#211]
When `ExecuteServiceFieldsSeparately` is false, a query through a navigation property of type `List<T>` fails. For example, given an entity like this:

```c#
class Customer {
    // ....
    public List<Order> Orders { get; set; }
}
```

A query like the following works if `ExecuteServiceFieldsSeparately` is true:

```graphql
customers {
    orders {
        id    
    }
}
```

However, if `ExecuteServiceFieldsSeparately` is false, the output is an error like this:
> Field 'customers' - Expression of type 'System.Collections.Generic.List`1[Order]' cannot be used for parameter of type 'System.Linq.Expressions.ParameterExpression' of method 'System.Object WrapListFieldForNullCheckExec(System.Object, System.Linq.Expressions.ParameterExpression, System.Linq.Expressions.Expression, System.Collections.Generic.List`1[System.Linq.Expressions.ParameterExpression], System.Collections.Generic.IEnumerable`1[System.Object], System.Linq.Expressions.ParameterExpression, System.Object)' (Parameter 'arguments[1]')

**Comment by lukemurray** [comment]
@breyed If you could help get (this test)[https://github.com/EntityGraphQL/EntityGraphQL/blob/master/src/tests/EntityGraphQL.Tests/QueryTests/OptionsTests.cs#L38] is a state that fails as you see in you project, that would help. As my simple test there passes.

Thanks

**Comment by breyed** [comment]
PR #220 has additions to the test to make it more closely match what I'm encountering in production. The test still passes. The issue may be related to #206, which the test has a fix for but my production code doesn't. I'll close this issue for now and reopen if the problem comes back after release 4.
