### ISSUE TITLE
Extracting data from ICollection, List, etc. throws exception when null

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [EntityGraphQL/EntityGraphQL#221]
(Originally posted at https://github.com/EntityGraphQL/EntityGraphQL/issues/204#issuecomment-1223643790)

**Code**

```c#
#nullable enable
public class UserDbContext : DbContext {
   public DbSet<UserWrapper> UserWrappers { get; set; }
}

public class UserWrapper {
   public string Json { get; set; }
}

public class User {
    public ICollection<Role>? Roles { get; set; } = null;
}

services.AddGraphQLSchema<UserDbContext>(options =>
{
    options.ConfigureSchema = ConfigureSchema;
});

public static void ConfigureSchema(SchemaProvider<UserDbContext> demoSchema)
{
    demoSchema.AddType<User>("user", null).AddAllFields();

    // Add custom root fields
    demoSchema.UpdateQuery(queryType =>
    {
        queryType.ReplaceField(
            "users",
            new
            {
                ...
            },
            (db, args) => db.UserWrappers.Select(userWrapper => JsonConvert.DeserializeObject<User>(userWrapper.Json)).ToList(),
            "List of users"
        );
    });
}
```

**Query**
```
{"Query":" { users { roles { id } }"}
```

**Error**
```json
{"errors":[{"message":"Field 'users' - Value cannot be null. (Parameter 'source')"}]}
```

**Comment by lukemurray** [comment]
The built expressions do null check when there are service fields involved. As it kind of makes an assumption that without service fields the expression will be handled by EF. In this case you are using EF.

I think EF is choosing to run some of the expression in memory after fetching the data it can. Then either `JsonConvert.DeserializeObject<User>(userWrapper.Json)` returns `null` for an item or the deserialised item has a `null` `Roles` property.

Makes me think of two points
1. this should be better highlighted in the docs
2. there likely should be an option to have this happen regardless of service fields

Interesting you don't "need" a service. But, if you could change the field to use a service (like make a deserialiser service) it may work with the current release.

Interesting use case though that needs more thought. I originally thought it was going to be something simple!

**Comment by Bosch-Eli-Black** [comment]
@bzbetty Thanks for the fix 🙂  Do you agree that it's best to silently return nothing? I think that's probably the desired behaviour here, but I could also see an argument for having it throw.

**Comment by bzbetty** [comment]
Looking at my implemented fix on larger queries I do wonder if it's a performance hit. Currently doing some performance testing for other reasons so I'll investigate further.

**Comment by Bosch-Eli-Black** [comment]
@bzbetty Cool, thanks 🙂
