### ISSUE TITLE
Add support for subscription to select data across the whole query graph

### ISSUE THREAD

**Issue by lukemurray** [EntityGraphQL/EntityGraphQL#226]
Currently it executes execution against the data directly - like if you return an object form a mutation. If the client wants to select more data through relations etc you need to have it loaded. Or we do a similar thing to mutations with expressions and build a full query again.

**Comment by Zerdayne** [comment]
I'm gonna add my request in this issue as it is related to the topic.

Currently the full graph query needs to be implemented as T in IObservable<T>.

Is it possible to support something like the following as T?

```cs
public class SubscriptionEvent<TEntity>
{
    public SubscriptionEventType Type { get; set; }
    public Expression<Func<DbContext, TEntity>> Field { get; set; }
}

public enum SubscriptionEventType
{
    Add,
    Update,
    Delete,
}
```
