### ISSUE TITLE
Parser doesn't recognize property names that are enclosed in quotes

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [EntityGraphQL/EntityGraphQL#231]
I'm not sure if this is a bug or is part of the spec., but if I try to execute a GraphQL query that looks like this:

```graphql
{
   users(filters:
      {
         "$.id": "1234",
         "$.name": "test"
      }
   )
   {
      id
   }
}
```

I get this error:

```json
{"errors":[{"message":"Expected a `Name`-token, but found a `String`-token."}]}
```

My goal was to have an object in the GraphQL query that gets translated into a `Dictionary<string, string>` in C#, but parsing the GraphQL query fails when a property name is surrounded in double quotes.

That is, this works:
```
{
   example: "test"
}
```

This doesn't:
```json
{
   "example": "test"
}
```

When the property name contains special characters, I think it should be surrounded by double quotes:
```json
{
   "i:$a": "test"
}
```

I've worked around this by changing the structure of the graphQL query:
```
{
   users(filters:
      [
         {
            key: "$.id",
            value: 1234
          },
         {
            key: "$.name",
            value: "test"
          },
      ]
   )
   {
      id
   }
}
```

Anyway, just FYI 🙂  Would be cool if this worked, but working around it isn't too bad, either 🙂

**Comment by bzbetty** [comment]
does it work as a variable?

eg
```
{
query: "{
   users(filters: $test)
   {
      id
   }
}",
variables: {
  "test": 
      {
         "$.id": "1234",
         "$.name": "test"
      }
 }
}
```

**Comment by Bosch-Eli-Black** [comment]
@bzbetty Good question! 🙂  I didn't even know that GraphQL queries could have variables, haha 😄

I gave it a go, but I'm getting this error:

```json
{
   "errors": [
      {
         "message": "Value cannot be null. (Parameter 'expression')"
      }
   ]
}
```

Any idea what I might be doing wrong? 🙂

**Comment by lukemurray** [comment]
Post exactly what you did?

**Comment by Bosch-Eli-Black** [comment]
Sorry, just finally had a chance to get back to this, haha. Using variables works fine 🙂

e.g.
```graphql
query ($userFilter: filters)
{
   users(filters: $userFilter)
   {
      id
   }
}
```

**Comment by Bosch-Eli-Black** [comment]
Would you still be interested in fixing the original issue? If so, I've be happy to post a full repro 🙂

**Comment by lukemurray** [comment]
Closing, as I do not think this is covered by the spec (full JSON syntax inline in the args). Using the variables is the suggestion. If this comes up a lot we can look at it again
