### ISSUE TITLE
Two-level customized DB query fails

### ISSUE THREAD

**Issue by breyed** [EntityGraphQL/EntityGraphQL#239]
I'm using EntityGraphQL 4.0.0-beta1 with EF. On the root context is a property that returns `IQueryable<Entity>`. It works fine by itself. On `Entity`, I use `AddField` and `ResolveWithService` to add another property that returns `IQueryable<Entity2>` with the help of a DB context object (separate from the GraphQL root context).

The query fails with:

> Field 'entities' - Expression of type 'System.Linq.IQueryable\`1[Entity2]' cannot be used for parameter of type 'System.Linq.Expressions.ParameterExpression' of method 'System.Object WrapListFieldForNullCheckExec(System.Object, System.Linq.Expressions.ParameterExpression, System.Linq.Expressions.Expression, System.Collections.Generic.List\'1[System.Linq.Expressions.ParameterExpression], System.Collections.Generic.IEnumerable`1[System.Object], System.Linq.Expressions.ParameterExpression, System.Object)' (Parameter 'arguments[1]')

If the query is executed with `ExecuteServiceFieldsSeparately` false, a different error occurs:

> Field 'entities' - variable 'db' of type 'MyDbContext' referenced from scope '', but it is not defined"

A related problem is that with `ExecuteServiceFieldsSeparately` still false, if an added field on an Entity returns `IEnumerable<Entity3>`, a similar error to the first case occurs:

> Field 'entities' - Expression of type 'System.Collections.Generic.IEnumerable\`1[Entity3]' cannot be used for parameter of type 'System.Linq.Expressions.ParameterExpression' of method 'System.Object WrapListFieldForNullCheckExec(System.Object, System.Linq.Expressions.ParameterExpression, System.Linq.Expressions.Expression, System.Collections.Generic.List\`1[System.Linq.Expressions.ParameterExpression], System.Collections.Generic.IEnumerable\'1[System.Object], System.Linq.Expressions.ParameterExpression, System.Object)' (Parameter 'arguments[1]')

I tried reproducing the error in a unit test, but couldn't get it to fail. Perhaps the issue is specific to EF. If so, if there's a good way for me to add EF-based unit tests, I could give it a try.

**Comment by lukemurray** [comment]
Just wondering did this work in 3.0.5? I.e. is this a regression?

**Comment by breyed** [comment]
The same code didn't work under 3.x; however, other issues may have prevented execution from getting to this point.

I tried debugging the production app with the EntityGraphQL project included, so I could debug its source, but since the error happens within an expression call, the debugger wasn't much help (at least to me). @lukemurray  While a EF-based unit test would be ideal (assuming the problem is really EF specific), if it's not practical and you're interested in improving this aspect of EntityGraphQL, I'd be happy arrange to Live Share with you.

**Comment by lukemurray** [comment]
Thanks. 

I'm keen to get EF unit tests in.

**Comment by bzbetty** [comment]
believe I just ran into this one too.

```
            schemaProvider.UpdateType<Resource>(c =>
            {             
                c.ReplaceField(
                    "resourceWorkTimes",                     
                    ""
                )
                .ResolveWithService<ESPContext>(
                    (resource, db) => db.ResourceWorkTimes.Where(x => resource.Hierarchy.IsDescendantOf(x.Resource.Hierarchy))
                );
            });
```

-->
`
"message": "Field 'resource' - variable 'x' of type '...ResourceWorkTime' referenced from scope '', but it is not defined"`

Although i haven't touched ExecuteServiceFieldsSeparately, so it could be different.  This feels like a regression as it's very similar to the case mentioned in the docs themselves:

https://entitygraphql.github.io/docs/schema-creation/other-data-sources#connecting-back-to-the-core-context

**Comment by lukemurray** [comment]
This commit https://github.com/EntityGraphQL/EntityGraphQL/commit/099aad8cdb3b6c8f4dbc4b17b4727ba408dfb0f3 I reproduced an issue similar, but I could not get the same "variable ... referenced from scope .., but it is not defined" errors. I got a different error because it built an incorrect expression. This is fixed.

It would be helpful to see if the current master branch code fixes your issues or if you can add a unit test that reproduces it if it does not fix.

**Comment by Bosch-Eli-Black** [comment]
We're seeing a similar issue, but the repro steps are different. I've filed #264 for this 🙂

**Comment by Bosch-Eli-Black** [comment]
@lukemurray I believe we were encountering a similar issue as this bug's author, when using `ResolveWithService()` to add a field to a type, as we were getting the same error message: `Field '...' - variable '...' of type '...' referenced from scope '', but it is not defined"`

I can confirm that 099aad8 fixed this bug, at least in our case 🙂
