### ISSUE TITLE
Supplied variable '{name}' can not be applied to defined variable type '{argType.Type}'

### ISSUE THREAD

**Issue by bzbetty** [EntityGraphQL/EntityGraphQL#250]
This message is the bain of my life :) 

Especially when you get the parent types/field names back only

eg

"Field 'addPersonSingleArgument' - Supplied variable 'nameInput' can not be applied to defined variable type 'InputObject'"

The wrapped exception actually has a useful error message, can we expose that?

example: "The string 'yesterday' was not recognized as a valid DateTime. There is an unknown word starting at index '0'." |

**Comment by bzbetty** [comment]
have a PR in there, but it might expose too much info.



**Before**: Method 'where' expects parameter that evaluates to a 'System.Boolean' result but found result type 'System.String'

**After**: Method 'where' expects parameter that evaluates to a 'System.Boolean' result but found result type 'System.String' No coercion operator is defined between types 'System.String' and 'System.Boolean'.

**Before**: Field 'addPersonSingleArgument' - Supplied variable 'nameInput' can not be applied to defined variable type 'InputObject'
**After**: Field 'addPersonSingleArgument' - Supplied variable 'nameInput' can not be applied to defined variable type 'InputObject' The string 'yesterday' was not recognized as a valid DateTime. There is an unknown word starting at index '0'.

**Before**: Field 'addPersonInput' - Supplied variable 'names' can not be applied to defined variable type '[String]'
**After**: Field 'addPersonInput' - Supplied variable 'names' can not be applied to defined variable type '[String]' Unable to cast object of type '<>f__AnonymousType3`2[System.String,System.String]' to type 'System.Collections.IEnumerable'.

**Before**: Field 'nullableGuidArgs' - Supplied variable 'id' can not be applied to defined variable type 'ID'
**After**: Field 'nullableGuidArgs' - Supplied variable 'id' can not be applied to defined variable type 'ID' Invalid cast from 'System.String' to 'System.Guid'.

**Comment by lukemurray** [comment]
Does the first example give any more information? It just says it can't convert a string to a boolean 2 times right?

The second example is better. Could we simplify it to something like "Field 'addPersonSingleArgument' - Supplied string 'yesterday' for variable 'nameInput' was not recognized as a valid DateTime"?

Third one I'm not sure helps much either?

And the fourth one could be similar to the second one?

**Comment by bzbetty** [comment]
yeah agreed on all points, all i did was concat the exception messages and show the before/after.

One of them is useful, the others not so much, unsure if there's a way to find out more info without potentially duplicating the message.
