### ISSUE TITLE
Hook on the final execution of the expression 

### ISSUE THREAD

**Issue by bzbetty** [EntityGraphQL/EntityGraphQL#253]
split from #241 
> a quick win would be a hook on the final execution of the expression where you could than hook in any Decompile() or WithTranslation() type things.

> That hook would also allow people to add TagWith for #169

> And AsSplitQuery presumably (although that would might a good attribute too)

**Comment by lukemurray** [comment]
I looked into this quickly the other week. Won't be as "easy" as I thought and depending on the fields and the query the final expression may be an object not a list so we can't just add those method calls on as they work on `IQueryable<>`.

**Comment by lukemurray** [comment]
Basic `BeforeExecuting` is in 5.0
