### ISSUE TITLE
Null ClaimsPrincipal makes all access checks pass

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [EntityGraphQL/EntityGraphQL#254]
**Steps to reproduce**
Configure a field with `RequiresAllRoles()`:

```c#
schema.UpdateQuery(queryType =>queryType.ReplaceField(...).RequiresAllRoles("my_role"));
```

Call `ExecuteRequest()` with `user` set to `null`:
```c#
_schemaProvider.ExecuteRequest(query, _graphQLOverallSchema, HttpContext.RequestServices, null);
```

In this case, the `RequiresAllRoles()` check appears to be bypassed, and instead of getting the error `You are not authorized to access the 'example' field on type 'Query'.`, we get data back instead.

This feels to me like a bug (albeit a minor one 🙂). If I pass `null` for the `user` in `ExecuteRequest()`, I would expect that all fields that have been configured with `RequiresAllRoles()` would fail with an access denied message.

(I've tested this on `EntityGraphQL 3.0.5` but not on the 4.0 branch)

**Comment by Bosch-Eli-Black** [comment]
Relevant code: https://github.com/EntityGraphQL/EntityGraphQL/blob/51c6018b3365da314887fb40e1e102be87528d71/src/EntityGraphQL/Schema/RoleBasedAuthorization.cs#L27

**Comment by Bosch-Eli-Black** [comment]
Ooo, looks like 4.0 just got released recently, yay! ^_^

Confirmed that this has the same behaviour on 4.0 🙂

**Comment by lukemurray** [comment]
Hmm this is "by design". Might not be good design!

If you pass `null` it "assumed no access check should happen". If you pass a `user` "checks should happen".

At this stage (because the library has evolved a lots since access check were first introduced) I think a better is to always do checks if they are on fields/types and error on `null` user.

If we still want the ability to bypass access checks, making it more explicit via an execution option would be better.

**Comment by bzbetty** [comment]
Speaking of auth I was pondering the other day whether it made sense to have a mode that optionally filtered out fields instead of erroring.  I tmight be a bit more flexibly in complex situations where you'd otherwise need many different queries depending on what groups the user is in.

**Comment by lukemurray** [comment]
Yeh, it will still cause an error just different (field not found type). But more importantly it can filter them out from schema introspection.

**Comment by bzbetty** [comment]
> Yeh, it will still cause an error just different (field not found type). But more importantly it can filter them out from schema introspection.

I didn't mean filter that early, although I can certainly see a use in that.

I meant silently continue and remove from output like @include does

**Comment by Bosch-Eli-Black** [comment]
@lukemurray Sounds like a good approach to me 🙂

**Comment by lukemurray** [comment]
Changing in upcoming 5.0 release.

>Previously passing `null` for the `ClaimsPrincipal` in `ExecuteRequest()` would skip any authorization checks. All authorization checks are now done regardless of the `ClaimsPrincipal` value. Meaning `null` will fail if there is fields requiring authorization.

**Comment by Bosch-Eli-Black** [comment]
Sweet! 🙂
