### ISSUE TITLE
Directly returning Task

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [EntityGraphQL/EntityGraphQL#261]
This isn't a bug, but a note to @lukemurray 🙂

I noticed in https://github.com/EntityGraphQL/EntityGraphQL/commit/61258c0c8c1f4d3a31d7dc4ea9a4502d5446662c#diff-45a6b5c201bf9694f68b83e3ce510c347857781e0fe570cc308f4ce8306634cbR22 that some of the code has been changed from something like this:

```c#
public async Task<object?> ExecuteMutationAsync<TContext>(...)
{
	try
	{
		return await MutationField.CallAsync(...);
	}
	catch (EntityQuerySchemaException e)
	{
           ...
        }
}
```

to this:
```c#
public Task<object?> ExecuteMutationAsync<TContext>(...)
{
	try
	{
		return MutationField.CallAsync(...);
	}
	catch (EntityQuerySchemaException e)
	{
           ...
        }
}
```

(That is, `async` has been removed from `ExecuteMutationAsync()`)

With this change, the code will compile and run as expected, but there's a subtle difference: In the first example, if an exception is thrown inside of `MutationField.CallAsync()`, the stack trace in the exception will look like this:

```
MutationField::CallAsync()
GraphQLMutationField::ExecuteMutationAsync()
...
MyUserCode()
```

In the second example, where the `async` keyword has been removed, the stack trace will no longer include `GraphQLMutationField::ExecuteMutationAsync()` , and will look like this:

```
MutationField::CallAsync()
...
MyUserCode()
```

Essentially, removing `async` and directly returning the `Task` instead of `await`ing it is results in slightly improved execution time but can make debugging more difficult, because some methods won't show up in the stack trace when an exception is thrown.

Just FYI! 🙂

**Comment by lukemurray** [comment]
Thanks, I did understand that. I Was opting for slightly improved execution time (haven't measured it though) and having the compiler not generate extra unneeded async state machine code.

Happy to be convinced otherwise.

Does MS / Dotnet have a suggested way? I couldn't find anything.

**Comment by Bosch-Eli-Black** [comment]
I think that as long as you're aware of the implications, it's probably fine 🙂  Our team has gone back and forth on this. We're currently opting for just calling `async` everywhere, but that's partly because our code isn't really performance critical.

Here's a recommendation by David Fowler, which I suppose is sort of, kind of official, haha: https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#prefer-asyncawait-over-directly-returning-task

**Comment by Bosch-Eli-Black** [comment]
By the way, a few other suggestions, in case they're helpful 🙂

I'd recommend adding `<AnalysisMode>Recommended</AnalysisMode>` to each `.csproj` file. Without this, only the "minimal" C# warnings are shown, for backwards compatibility reasons.

Adding `<ImplicitUsings>enable</ImplicitUsings>` to each project is also nice, as it cuts down on repetitive `using` statements a bit 🙂

Finally, some analyzers that you might be interested in:
* https://www.nuget.org/packages/Microsoft.VisualStudio.Threading.Analyzers/
* https://github.com/DotNetAnalyzers/IDisposableAnalyzers
* https://github.com/semihokur/AsyncFixer

If you use the AsyncFixer analyzer, it has an `AsyncFixer01` warning that's for exactly what we're discussing here: Whether or not to warn when `async` is used "unnecessarily". By default, it's turned on, but we turn it off via `.editorconfig`:
```
# AsyncFixer01: Unnecessary async/await usage
dotnet_diagnostic.AsyncFixer01.severity = none
```

**Comment by lukemurray** [comment]
thanks for these

**Comment by Bosch-Eli-Black** [comment]
Np! 🙂
