### ISSUE TITLE
List<...> not queryable

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [EntityGraphQL/EntityGraphQL#263]
I've been trying to work on some bug repros, but I've having trouble getting a minimal example with EntityGraphQL up and running.

I figured I'd set up a context that has `List<User>` inside it, instead of using `DbSet<User>`, but whenever I query the user, I get no fields back.

Here's the full code:

```c#
public class User
{
    public string Name { get; set; }
}

public class UsersContext
{
    public List<User> Users { get; set; }
}

public class Program
{
    public static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);

        builder.Services.AddControllers();

        builder.Services.AddGraphQLSchema<UsersContext>();

        var app = builder.Build();
        app.UseHttpsRedirection();
        app.UseCors(builder =>
        {
            builder
            .WithOrigins("*")
            .WithMethods("GET")
            .AllowAnyHeader();
        });
        app.UseAuthorization();
        app.MapControllers();
        app.Run();
    }
}

[ApiController]
[Route("[controller]")]
public class GraphQLController : Controller
{
    private readonly SchemaProvider<UsersContext> _schemaProvider;
    public GraphQLController(SchemaProvider<UsersContext> schemaProvider)
    {
        _schemaProvider = schemaProvider ?? throw new ArgumentNullException(nameof(schemaProvider));
    }

    [HttpPost]
    public async Task<object> Post([FromBody] QueryRequest query)
    {
        var usersContext = new UsersContext
        {
            Users = new List<User>
            {
                new User
                {
                    Name = "test user"
                }
            }
        };

        return await _schemaProvider.ExecuteRequestAsync(query, usersContext, HttpContext.RequestServices, HttpContext.User);
    }
}
```

And my query:
```
{ users { name } }
```

I get back an array with one element (as expected), but it doesn't have a `name` field, which is unexpected:

```json
{"data":{"users":[{}]}}
```

The strange thing is that if I trace through the code, `SchemaProvider::ExecuteRequestAsync()` is returning what I'd expect:

![image](https://user-images.githubusercontent.com/37427589/193793963-1c45187e-7ec8-4730-89f4-fb85d84f6429.png)

(Note the red dash sign next to the "name" property. Not sure what VS is trying to tell us, there. Maybe that it's a private member?)

I'm using the latest version of HEAD, but I'm also encountering this issue on 4.0.

Any ideas? 🙂  Is directly having `List<...>` in the GraphQL context not supported, or am I missing something obvious?

Thanks! 🙂

**Comment by lukemurray** [comment]
By default the JSON serialiser does not serialise fields.

https://entitygraphql.github.io/docs/getting-started#configuring-systemtextjson

Same for JSON.NET if you are using that.

**Comment by Bosch-Eli-Black** [comment]
Thanks, that fixed it! I feel dumb 😆
