### ISSUE TITLE
Entity transformations after fetching

### ISSUE THREAD

**Issue by thomasbeste** [EntityGraphQL/EntityGraphQL#267]
Hello,

I am using EntityGraphQL to query EF.Core, and i am happy with it's ease of use, and it's ability to actually only query the set of fields needed.

My business case demands the ability to transform the returned database objects into a domain object. I have tried different approaches, like ResolveWithService, a simple .Select(returnedobject => newobject) and so on. Whenever i change my code to do these things, i can no longer get my query to only query for the fields the original gql query asked for...

I would like the EF.Core to only query the needed fields, but also the ability to transform the result to a new object before i return it to the client.

Is this possible?

**Comment by bzbetty** [comment]
Can you describe your business case more? What value does the domain object get you if you just end up serialising it to JSON for the endpoint?

**Comment by thomasbeste** [comment]
Hello, and thanks alot for getting back to me.

From my personal point of view, it will not really add any value. 
It adds complexity, and forces me to implement more code to map, filter, sort and so on.

However, since the domain architects i am working with, has domain object graphs, which does not match the EF.Core graphs, i am looking into the ability to transform the objects into another structure, which is then exposed to other API consumers.

query(id){field1 field2} -> query ef.core for only field1, field2  -> transform result into another object structure.

But the more i use this library, the more i am convinced that we should not transform the objects, if we want to gain the full benefit of this library and ef.core combined...

I just wanted to make sure that there was not something obvious i missed, before i go with this conclusion.
