### ISSUE TITLE
Make JObjectTypeConverter and JTokenTypeConverter public instead of internal?

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [EntityGraphQL/EntityGraphQL#292]
We're using Newtonsoft.Json and we were running into the error `"Supplied variable '...' can not be applied to defined variable type '...'"`.

https://github.com/EntityGraphQL/EntityGraphQL/issues/125#issuecomment-1152819373 pointed me to [this test](https://github.com/EntityGraphQL/EntityGraphQL/blob/master/src/tests/EntityGraphQL.Tests/SerializationTests.cs#L25), which makes use of the classes `JObjectTypeConverter` and `JTokenTypeConverter`. Copying and pasting these classes into our project seemed to fix this error.

These classes are currently `internal`: https://github.com/EntityGraphQL/EntityGraphQL/blob/c75ed453633b34684329867e0c39a70845e26cd5/src/tests/EntityGraphQL.Tests/SerializationTests.cs#L160

Would it make sense to make these classes be `public`, so that we could import them from the EntityGraphQL NuGet? 🙂

**Comment by bzbetty** [comment]
those are internal classes in the test project, they're specifically not in EQL base itself as EQL does not have a reference to Newtonsoft (as mentioned https://entitygraphql.github.io/docs/serialization-naming/newtonsoft-json)

**Comment by Bosch-Eli-Black** [comment]
Oh, right 😄  Thanks 🙂
