### ISSUE TITLE
No mapping for JsonDocument property

### ISSUE THREAD

**Issue by dmikov** [EntityGraphQL/EntityGraphQL#298]
EntityGraphQL.Compiler.EntityGraphQLCompilerException: 'No schema type found for dotnet type JsonElement. Make sure you add it or add a type mapping'

**Comment by lukemurray** [comment]
Do you have more info on how to reproduce this? By default the library handles `JsonElement` objects passed in a parameters.

**Comment by lukemurray** [comment]
Any updates on this error?

**Comment by lukemurray** [comment]
Closing as I can not reproduce. Please reopen with more information if this is still an issue
