### ISSUE TITLE
[Feature] Add the ability to secure the GraphQL Endpoint in ASP.net Core

### ISSUE THREAD

**Issue by RubberChickenParadise** [EntityGraphQL/EntityGraphQL#304]
Currently, due to the use of mapping endpoints, there is not an easy way to secure the entire graphql endpoint.  The object level security works but in cases where only authenticated users should have access to any data, even the schema, there is no easy way to accomplish this.

Adding the ability to apply an Authorization Policy to the endpoint itself would be very helpful for the security needs of several applications.

**Comment by lukemurray** [comment]
merged coming shortly in the 5.0 release
