### ISSUE TITLE
Working without declaring DbSet in DbContext

### ISSUE THREAD

**Issue by StefanoVuerich** [EntityGraphQL/EntityGraphQL#312]
Good morning,

is it possible to use the library without declaring DbSet properties on DbContext?

Somethink like following:

```
public class DemoContext : DbContext {

  public DemoContext(DbContextOptions options) : base(options)
  {
  }

  protected override void OnModelCreating(ModelBuilder builder) {
    builder.ApplyConfigurationsFromAssembly(typeof(DemoContext).Assembly);
  }
}
```

At the moment I'm getting exception:

EntityGraphQL.Compiler.EntityGraphQLCompilerException: 'Field 'xxx' not found on type 'Query''

Thank you!

**Comment by lukemurray** [comment]
Hi Stefano,

No you can not. EntityGraphQL works by building dotnet expressions. E.g.

{
   SomeEntities { id }
}

Will compile to (ctx) => ctx.SomeEntities.Select(e => id = e.Id)

Where ctx will be the instance of your DbContext. If SomeEntities is not a
property or field, EntityGraphQL cannot build the expression.

I.e. EntityGraphQL does not do anything with SQL - it only builds
expressions and lets EF handle the rest.

Cheers
Luke

**Comment by StefanoVuerich** [comment]
Hi Luke,

I manage my problem using these classes:

```c#
public class GraphQLSchemaBuilder<T> where T : class
{
    public static void ConfigureSchema(SchemaProvider<GraphQLDbContext> schema)
    {
        var instance = Activator.CreateInstance<T>();
        var name = instance.GetType().Name;

        if (!schema.HasType(instance.GetType().Name))
        {
            schema.AddType<T>(name).AddAllFields();
        }

        schema.UpdateQuery(queryType =>
        {
            queryType.AddField(name, db => db.Set<T>(), $"List of {name}");
        });

        System.IO.File.WriteAllText("schema.graphql", schema.ToGraphQLSchemaString());
    }
}
``` 

Then I can call the ConfigureSchema method using refletion:

```c#
builder.ConfigureServices((context, services) =>
{
    services.AddDbContext<GraphQLDbContext>(/*config the db context*/);

    services.AddGraphQLSchema<GraphQLDbContext>(options =>
    {
        options.ConfigureSchema = schemaBuilder =>
        {
            var myModels = Assembly.GetEntryAssembly().GetTypes().Where(/* logic to get only models i want to manage through graphql */)

            myModels .ForEach(m=>
            {
                Type generic = typeof(GraphQLSchemaBuilder<>);
                var model = Activator.CreateInstance(m);
                Type[] typeArgs = { model.GetType() };
                Type constructed = generic.MakeGenericType(typeArgs);
                var method = constructed.GetMethod("ConfigureSchema");
                method.Invoke(Activator.CreateInstance(constructed), new object[] { schemaBuilder });
            });
        };
    });
});
``` 
@lukemurray What you think about this? I tried and it is working, do you see any downside?

Thanks

**Comment by lukemurray** [comment]
OK. I didn't realise you just wanted to use `ctx.Set<MyEntity>()` as the root of the expression.

Yes that will work and should be no issues. It is the same as manually adding them all but using reflection to auto add the ones you want if you don't want them defined at the `DbContext` or manually write out each one.
