### ISSUE TITLE
Update doc for Mutatation GraphQLValidator for versions >= 5.0.0

### ISSUE THREAD

**Issue by dhruv217** [EntityGraphQL/EntityGraphQL#316]
After the  upgrade from 4.x to 5.x the Graph QL Validator services is not automatically added to Dependency Injection and needs to be separately added.

But the only implementation of the service as argument shown in the documentation for a mutation which is :
`
[GraphQLMutation]
  public Expression<Func<MyDbContext, Movie>> AddActor(MyDbContext db, ActorArgs args, GraphQLValidator validator)
  {}
`
results in an error that the service GraphQLValidator cannot be resolved from Dependency Injection. Updating it like so seems to fix the issue.
`
[GraphQLMutation]
  public Expression<Func<MyDbContext, Movie>> AddActor(MyDbContext db, ActorArgs args, IGraphQLValidator validator)
  {}
`
GraphQLValidator  -> IGraphQLValidator in method parameters.

I believe this should be updated in the documentation.
Happy to Submit a PR for the same.

**Comment by lukemurray** [comment]
Thanks, PR would be welcome
