### ISSUE TITLE
Customize the schema

### ISSUE THREAD

**Issue by Lucoky** [EntityGraphQL/EntityGraphQL#317]
I'm struggling to grasp how I should adjust my schema. In the documentation, the schema is initially defined every times it's use. However, all the examples suggest that you can add, edit, or remove types by defining another schema. Do I need to create a new class called CustomSchema and then set the schema in the constructor like this: 'schema = SchemaBuilder.FromObject<DemoContext>()'? I'm finding it a bit challenging to understand how to customize it effectively.
Can someone help me please?

**Comment by lukemurray** [comment]
Generally a schema is created once at startup. `SchemaProvider<TContextType>` maps a GraphQL schema to dotnet types and expressions. A common use case is using a `DbContext` as the underlying dotnet type. `SchemaBuilder.FromObject<MyDbContext>();` will create a GraphQL schema that maps to the types and properties of `MyDbContext`. 

If there are properties you do not want to expose in your GraphQL schema you can mark them with `[GraphQLIgnore]` or remove them from the schema

```cs
public class MyDbContext
{
    public DbSet<Project> Projects { get; set; }
}

var schema = SchemaBuilder.FromObject<MyDbContext>();
schema.UpdateType<Project>(type =>
{
    type.RemoveField("createdBy");
});
```

You'll find other methods to replace fields or add new fields. E.g. (silly example)
```cs
schema.UpdateType<Project>(type =>
{
    type.AddField("secondsSinceCreated", project = > (DateTime.Now - project.Created).TotalSeconds);
});
```

If you are using `EntityGraphQL.AspNet` you can configure your schema on startup

```cs
services.AddGraphQLSchema<DemoContext>(options =>
{
    options.ConfigureSchema = (schema) => {
        // make changes to your schema here.
    };
});
```

The demo project has an example of this [here](https://github.com/EntityGraphQL/EntityGraphQL/blob/master/src/examples/demo/Startup.cs#L66) and [here](https://github.com/EntityGraphQL/EntityGraphQL/blob/master/src/examples/demo/GraphQLSchema.cs#L12).

If you can share more about what you are trying to achieve or how you want to customise the schema I can more directly help. Also it would be great to hear what isn't making sense in the [documentation](https://entitygraphql.github.io/docs/schema-creation/) so I can make it clearer.

**Comment by lukemurray** [comment]
Closing unless you have more questions.
