### ISSUE TITLE
Recommended way to restrict access to entities based on authenticated user

### ISSUE THREAD

**Issue by crjc** [EntityGraphQL/EntityGraphQL#326]
I need to restrict access to entities depending on the authenticated user. For example, the `post` entity might have a 'userId', so only posts with the user's id should be returned by the graphql endpoint.

I haven't found a way to do this in the documentation, so I'm guessing there's no recommended method to actually achieve this? I'm currently looking at modifying the Filter field extension, but I'm wanting to check if there's a better way?

**Comment by crjc** [comment]
Duplicate of https://github.com/EntityGraphQL/EntityGraphQL/issues/78.

Looks like the best solution is to use ReplaceField

**Comment by bzbetty** [comment]
Can also use underlying platform features like Global Query Filters (https://learn.microsoft.com/en-us/ef/core/querying/filters) and Row level security (https://github.com/Huachao/azure-content/blob/master/articles/app-service-web/web-sites-dotnet-entity-framework-row-level-security.md)
