### ISSUE TITLE
How to configure an argument

### ISSUE THREAD

**Issue by nitish-mittal-maersk** [EntityGraphQL/EntityGraphQL#329]
So I have the schema something like:
```csharp
public class List
{
  public Guid Id {get; set;}
  public string Number {get; set;}
  //other props
}
```
The schema generated uses Id as an argument:
`list ( id ID! ) List`

I want to remove `id` and use `Number`  instead as argument. How can I achieve that?

**Comment by lukemurray** [comment]
I hope some of these links help explain things. [This one](https://entitygraphql.github.io/docs/schema-creation/#building-a-full-schema) describes why the `id` field is created.

You can turn that off - for all list fields - with the `SchemaBuilderOptions`

```c#
services.AddGraphQLSchema<DemoContext>(options =>
{
    options.AutoCreateFieldWithIdArguments = false;
});
```

However if you want to just change that one field. I hope this [link will help](https://entitygraphql.github.io/docs/schema-creation/fields). Basically you replace the field.

```c#
services.AddGraphQLSchema<DemoContext>(options =>
{
    options.PreBuildSchemaFromContext = schema =>
    {
        // Customise schema
        schema.Query().ReplaceField(
            "list", // field name
            new { number = ArgumentHelper.Required<string>() }, // define field arguments
            (ctx, args) => ctx.List.Where(l => l.Number == args.number).FirstOrDefault(), // resolve expression
            "Return a list element by number" // description
         );
    };
});
```

**Comment by nitish-mittal-maersk** [comment]
@lukemurray 
Thanks this helps.
