### ISSUE TITLE
Offset Paging issue with two top level fields returning the paged object

### ISSUE THREAD

**Issue by MarkRuseEL** [EntityGraphQL/EntityGraphQL#358]
I have a pagination issues that might well be linked to #352.

I have a schema as follows and have implemented Offset paging for the Property object

```typescript
type Query {
  	"""Service based Property by category resolver"""
	propertiesByCategory(categoryId: Int!, skip: Int, take: Int): PropertyPage
	"""Service based Property by phase resolver"""
	propertiesByPhase(phaseId: Int!, skip: Int, take: Int): PropertyPage
...
...
...
type PropertyPage {
	"""True if there is more data after this page"""
	hasNextPage: Boolean!
	"""True if there is more data before this page"""
	hasPreviousPage: Boolean!
	"""Return a Property by its Id"""
	item(id: Int!): Property
	"""Items in the page"""
	items: [Property]!
	"""Count of the total items in the collection"""
	totalItems: Int!
}
``` 
This was generated by this schema
```c#
                queryType.AddField("propertiesByPhase",
                    new
                    {
                        phaseId = ArgumentHelper.Required<int>()
                    },
                    (db, args) => db.Properties.Where(p => p.Category.PhaseId == args.phaseId),
                    "Service based Property by phase resolver")
                .UseOffsetPaging();

                queryType.AddField("propertiesByCategory",
                    new
                    {
                        categoryId = ArgumentHelper.Required<int>()
                    },
                    (db, args) => db.Properties.Where(p => p.Category.Id == args.categoryId),
                    "Service based Property by category resolver")
                .UseOffsetPaging();
``` 

On running this query
```typescript
query PropertiesByPhase {
    propertiesByPhase(phaseId: 1, skip: 0, take: 5) {
        hasPreviousPage
        hasNextPage
        totalItems
        items {
            id
            reference
            description
            isRemoved
            categoryId
        }
    }
}
``` 
I get the error
```javascript
{
    "errors": [
        {
            "message": "Field 'propertiesByPhase' - Could not find arguments for field propertiesByCategory in compile context."
        }
    ]
}
``` 
Interestingly, the propertiesbyCategory  continues to work correctly with both defined and if I comment out either the other will work.  I saw that @lukemurray has moved the other ticket into 5.3 so wanted to add this in case this slightly differing use case is helpful when finding a fix,, or to find out if it isn't related and I am doing something wrong.

**Comment by lukemurray** [comment]
Interesting.

Adding the paging adds a schema type of `OffsetPaging<Property>` and there is only 1 of that type in the schema. It has the field `items`. The issue is internal to how EntityGraphQL passes the arguments you define at the `propertiesByPhase` field down to the `items` field means the second one overwrites the first one!

**Comment by lukemurray** [comment]
It would be great if you could try the latest master branch out with your project. It fixes using the extensions on multiple fields that return the same type.

**Comment by MarkRuseEL** [comment]
Thanks for the commit.  I tried again to sort out antlr as I am now on a new machine since I posted this  https://github.com/EntityGraphQL/EntityGraphQL/issues/347#issuecomment-1980240975
but getting stuck on the same issue where the .m2 downloads but not the java runtime.  I went further this time and I can actually run with this
```
java -cp c:\Javalib\antlr-4.13.1-complete.jar org.antlr.v4.Tool
``` 
but for some reason it won't work when rebuilding the solution

**Comment by lukemurray** [comment]
You should be able to comment out this section in `EntityGraphQL.csproj`

```
<ItemGroup>
    <Antlr4 Include="Compiler/Grammer/EntityQL.g4">
      <Package>EntityQL.Grammer</Package>
      <Listener>false</Listener>
      <Visitor>True</Visitor>
      <JavaExec>/usr/bin/java</JavaExec>
    </Antlr4>
  </ItemGroup>
```

**Comment by MarkRuseEL** [comment]
Thanks for this.  Commenting out didn't work but adding my java.exe into the JavaExec property worked at treat so I have a full build.  My solution had moved on a bit but reverted back to when I had the issue and can still the same issue.  I commented out my references to the release version and did a project reference to the aspnet dll built from this project.  One thing that surprised me was I needed to revert my new changes from Resolve (as I had upgraded them for 5.2) back to ResolveWithService which didn't make much sense to me so not 100% certain I have performed a fair test

**Comment by lukemurray** [comment]
That is strange. I would think you did not update the branch to the latest (git pull)? Had you previously checked out the repo (or cloned it)? You can see that the latest code in the master branch of the repo has `Resolve` methods - https://github.com/EntityGraphQL/EntityGraphQL/blob/master/src/EntityGraphQL/Schema/FieldToResolve.cs

If you cloned it, you'll need to merge that main repo's master branch back in.

**Comment by MarkRuseEL** [comment]
Yes this is quite strange but almost got to the bottom of it - had the latest code but a hidden nuget ref back to 5.1.1 that I only found when decompiling the class with resharper.  Now the Resolve is coming up correctly in my project.  My project now runs with refs back to the net8 debug versions of EGQL.  Everything runs but now getting a system.io.FileNotFoundException when trying to connect postman to refresh the schema :(.   Fed up with it now but will take a look tonight to see if I can unkink my env further

**Comment by MarkRuseEL** [comment]
scrub the above - couldn't let it go - found out that the issue was I needed hotchocolate as ref in my project as EGQL relies on this.  I have tested and can confirm that both queries are working perfectly.  Appreciate you taking the time to make this fix

**Comment by lukemurray** [comment]
Thanks for confirming. Strange you had to reference anything else. I just reference `<ProjectReference Include="/path/to/EntityGraphQL.csproj"/>` or `<ProjectReference Include="/path/to/EntityGraphQL.AspNet.csproj"/>` and everything works (replacing the `PackageReference`.

Anyway. Thanks again. I have a few more things I want to try to get into 5.3 before publishing a new package.

**Comment by MarkRuseEL** [comment]
Thanks Luke, I was referring to the dll directly which was probably a bit overkill - I have project referenced in and all okay.  No worries on the 5.3 timeline - I'll keep in this config until it goes mainline
