### ISSUE TITLE
DateOnly and Spacial Data types not supported

### ISSUE THREAD

**Issue by VZhangTylerTech** [EntityGraphQL/EntityGraphQL#359]
Need to know if they are going to be supported or developers need to do create converters.

**Comment by lukemurray** [comment]
Yes these should be added.

In the meantime, depending on what you want to do with them it is easy to support now.

Returning them in a query result should be just adding it as a scalar value if that is how you want it represented

```cs
schemaProvider.AddScalarType<DateOnly>("DateOnly", "Represents a date only without time");
```

And taking them in as input arguments means writing a simple converter like [here](https://entitygraphql.github.io/docs/serialization-naming/newtonsoft-json)

**Comment by lukemurray** [comment]
Also, which spacial types do you mean? `DateOnly` and `TimeOnly` certainly make sense to add.

**Comment by lukemurray** [comment]
5.3 will have `DateOnly` & `TimeOnly` registered as defaults. You an easily add more or change that following the [docs](https://github.com/EntityGraphQL/EntityGraphQL/blob/master/docs/docs/schema-creation/scalar-types.md)
