### ISSUE TITLE
Add support to allow sort on owned entity properties

### ISSUE THREAD

**Issue by PhilippeWaeber** [EntityGraphQL/EntityGraphQL#362]
I'm looking for some guidance on how (and where) to best add support sorting for owned entitites.

What I've got (removed not relevant code/properties):

Models:
```cs
public class Product
{
    public uint Id { get; set; }
    public LocalizedText Description { get; set; } = LocalizedText.Default;
}

public record LocalizedText : Localized<string>
{
    public static LocalizedText Default => new() { De = "{default}" };
}

public abstract record Localized<T>
{
    public required T De { get; set; }
    public T? Fr { get; set; }
    public T? It { get; set; }
    public T? En { get; set; }

    public T Current =>
        CultureInfo.CurrentCulture.TwoLetterISOLanguageName switch
        {
            "de" => De,
            "fr" => Fr ?? De,
            "it" => It ?? Fr ?? De,
            "en" => En ?? De,
            _ => De
        };
}
```

EF `DbContext` configuration:
```cs
internal class ProductConfiguration : IEntityTypeConfiguration<Product>
{
    public override void Configure(EntityTypeBuilder<Product> builder)
    {
        builder.HasKey(product => product.Id);
        builder.OwnsOne(product => product.Description);
    }
}
```
When letting EF create the DB, following table is created (Note that the descriptions are part of the table itself)
![image](https://github.com/EntityGraphQL/EntityGraphQL/assets/156912309/9a2c208f-867b-4f7c-bb93-26a6edc941d7)

The GraphQL field is set up with:
```cs
schema.ReplaceField("products", 
                    ctx => ctx.Products, 
                    "Return a list of products. Supports searching, filtering, sorting and paging.")
      .UseSort()
      .UseOffsetPaging(DefaultPageSize, MaxPageSize);
```

Now I would like to be able to sort by the language dependent description column.

From a SQL point of view, this is as simple as applying e.g. `ORDER BY Description_De` but this possibility is not available for GraphQL sort.

The GraphQL query could look like this:
```graphql
{
  products(
    sort: [{ description.de : DESC }]
    skip: 0
    take: 20
  ) {
    totalItems
    items {
      description {
        de
        fr
      }
    }
  }
}
```

What do you reckon would be the 'best' way to support this?
- Adapt/extend [SortExtension](https://github.com/EntityGraphQL/EntityGraphQL/blob/master/src/EntityGraphQL/Schema/FieldExtensions/Sorting/SortExtension.cs) to support this?
- Add another way to sort, where a string like `Description.De` could be specified, which can be used by EF?
- Something else?

**Comment by lukemurray** [comment]
How would you do this in LINQ? Is it this

```cs
var results = dbContext.Products.OrderBy(p => p.Description.De);
```

If that is the case I think updating the SortExtension to better support expressions as the key. It just takes the  `[{ field : DESC }]` and turns it into the `.OrderByDescending(p => p.Field)`.

It should already look up the expression of `field` in the schema to know it is `p.Field` in dotnet.

So potentially just adding those fields to the `Product` type in the schema.

```cs
schema.UpdateType<Product>(type => {
    type.AddField("description_de", p => p.Description.De, "Description in De locale");
    type.AddField("description_fr", p => p.Description.De, "Description in Fr locale");
});
```

If this doesn't work, it should be fixable in the `SortExtension`.

Another way without adding the fields to `Product` would involve modifying `SortExtension` - you can pass in sort fields

```cs
schema.ReplaceField("products", 
                    ctx => ctx.Products, 
                    "Return a list of products. Supports searching, filtering, sorting and paging.")
      .UseSort((Product p) => new
                {
                    p.Product.De,
                    p.Product.Fr
                })
      .UseOffsetPaging(DefaultPageSize, MaxPageSize);
```

But I do not know how it will handle the non-simple expression

**Comment by lukemurray** [comment]
I just push a change that addresses this allowing this way to work.

```cs
chema.ReplaceField("products", 
                    ctx => ctx.Products, 
                    "Return a list of products. Supports searching, filtering, sorting and paging.")
      .UseSort((Product p) => new
                {
                    DescriptionDe = p.Description.De,
                    DescriptionFr = p.Description.Fr
                })
      .UseOffsetPaging(DefaultPageSize, MaxPageSize);
```

**Comment by PhilippeWaeber** [comment]
Amazing, thanks a lot!

This was indeed the LINQ query I'm expecting `var results = dbContext.Products.OrderBy(p => p.Description.De);`
