### ISSUE TITLE
Filtering syntax with first and orderBy operators

### ISSUE THREAD

**Issue by wonglae** [EntityGraphQL/EntityGraphQL#365]
Is it possible to combine below 2 filters?
```
List.first(filter?) - Return the first item from a list. Optionally by a filter
List.orderBy(field) - Order the list by a given field
```
My table has a related one-to-many foreign table and I would like to get the max value of a field in foreign table, can I sort the foreign table field and get the first element?

**Comment by lukemurray** [comment]
You can, there are likely edge cases that may fail. That expression filtering needs a revisit for a few things.

What is it you want to do? Here is a weird example

```
query {
    projects(filter: "tasks.orderByDesc(hoursEstimated).first().hoursEstimated > 0") {
        name tasks { id }
    }
}
```

But this filters the list of projects. If you want to return the max in a query you likely want to add a field to the schema.

```cs
schema.UpdateType<Project>(type => {
    type.AddField("maxHoursEstimatedForSingleTask", project => project.Tasks.Max(t => t.HoursEstimated), "Get the max hours estimated for a single task");
});
```

I hope that helps, otherwise if you can share more details - data model, query you are trying - I can help further.

**Comment by wonglae** [comment]
The custom field approach looks execilent, it's exactly what I want to do. Thanks for the suggestion.
Speaking of the example:
```
query {
    projects(filter: "tasks.orderByDesc(hoursEstimated).first().hoursEstimated > 0") {
        name tasks { id }
    }
}
```
do you mean "first()" returns only the first project object after sorting? What I wanted to do is return project list, in each project return the first task (I have many task linked to one project). the custom field approach looks good but it will be better if I don't need to add custom fields to the query.

**Comment by lukemurray** [comment]
The field `projects` will return a list of projects. The filter just filters them. The above example is like writing this

```cs
var projects = db.Projects.Where(p => p.Tasks.OrderByDesc(t => t.HoursEstimated).First().HoursEstimated > 0).ToList();
```

To only return the first task as a field, you need to define a field which is the `AddField` example above. Or to return the whole task

```cs
schema.UpdateType<Project>(type => {
    type.AddField("firstTasK", project => project.Tasks.First(), "Get the task"); // replace expression with what you need
});
```

**Comment by wonglae** [comment]
Hmm, is it possible to add custom fields using something like GraphQLFieldAttribute? the attribute doesn't seem to support expression currently.

**Comment by lukemurray** [comment]
It is but it has limitations.

https://entitygraphql.github.io/docs/library-compatibility/expression-reuse
https://entitygraphql.github.io/docs/schema-creation/fields#note-about-method-execution-with-ef

Basically if you want the field to get compiled to something EF likes you'll need to use something similar to [EntityFrameworkCore.Projectables](https://github.com/koenbeuk/EntityFrameworkCore.Projectables) as highlighted in the above links.

**Comment by wonglae** [comment]
How to register sort after the field added? I'm using [UseSort] attribute to automatically add fields.

schema.UpdateType<Project>(type => {
    type.AddField("firstTasK", project => project.Tasks.First(), "Get the task"); // replace expression with what you need
});

**Comment by wonglae** [comment]
BTW it seems Sort feature doesn't respect GraphQLIgnore attribute. I tagged some fields as ignored but they still show up in the input type of sort

**Comment by lukemurray** [comment]
`[UseSort]` and the other attributes work when the schema is automatically built with `SchemaBuilder`. If you are adding fields manually - which is common. You call `.UseSort()`

```cs
schema.ReplaceField("people",
    ctx => ctx.People,
    "Return a list of people. Optional sorted")
    .UseSort();
```

There are options in that call to customise which fields are used in the sort input etc.

You're right the attribute way should respect the ignore attribute

**Comment by wonglae** [comment]
Because I was using UseOffsetPagingAttribute it complains the return type is not a collection anymore when I call UseSort(). Some misalignment in schema is okay so far. The problem is Sort extension doesn't apply the custom expression I alternated for field firstTask.

I think I found a solution / work around by changing below line:

`
                        expression = Expression.Call(
                            methodType!,
                            method,
                            new Type[] { listType!, schemaField.ReturnType.TypeDotnet },
                            expression,
                            Expression.Lambda(Expression.PropertyOrField(sortField, fieldInfo.Name), listParam)
                        );
`
in https://github.com/EntityGraphQL/EntityGraphQL/blob/5.2.1/src/EntityGraphQL/Schema/FieldExtensions/Sorting/SortExtension.cs

to
`
                        expression = Expression.Call(
                            methodType!,
                            method,
                            new Type[] { listType!, schemaField.ReturnType.TypeDotnet },
                            expression,
                            Expression.Lambda(schemaField.ResolveExpression!, schemaField.FieldParam!)
                        );
`
But it seems latest code has been changed.

**Comment by lukemurray** [comment]
Paging changes the shape of the objects etc. as you see in the resulting schema. As outlined in the [docs](https://entitygraphql.github.io/docs/field-extensions/) paging needs to be last.

>When combining multiple extensions together on a single field order matters. The correct order is for the provided extensions is

Filter -> Sort -> Paging

Or are you saying you are are applying paging last and it still fails?

**Comment by wonglae** [comment]
I changed to call UseSort() manually so trying to say I need to call UseOffsetPaging() manually as well.
Will you consider applying the fix which uses the expression registered to the field:
`expression = Expression.Call( methodType!, method, new Type[] { listType!, schemaField.ReturnType.TypeDotnet }, expression, Expression.Lambda(schemaField.ResolveExpression!, schemaField.FieldParam!) );`

**Comment by lukemurray** [comment]
Sorry, I am not fully following what is broken or not working, can you make a unit test that reproduces the issue? That way I can fix it and not break it in the future.

Using `schemaField.ResolveExpression` makes sense and doesn't break anything, however I'd still love to better understand what is failing today in a test.

**Comment by wonglae** [comment]
Okay, I will make a UT to repro the issue and maybe submit a PR when I get some time.

Basically scenario is:
I registered a type 'Project' and then I added/updated a field using custom expression:

```
schema.UpdateType<Project>(type => {
    type.AddField("maxHoursEstimatedForSingleTask", project => project.Tasks.Max(t => t.HoursEstimated), "Get the max hours estimated for a single task");
});
```

And then I register Sort (It seems I need to register sort after field modifications to Project done, correct?)
`schema.GetField("project").UseSort();
`

And then it seems when I sort on the field 'maxHoursEstimatedForSingleTask' the query uses the fields 'maxHoursEstimatedForSingleTask' as if it's a db column
```
query {
  project(sort: [maxHoursEstimatedForSingleTask: ASC]) {
    maxHoursEstimatedForSingleTask
  }
}
```

Got this error when I run the query:
`The specified type member 'maxHoursEstimatedForSingleTask' is not supported in LINQ to Entities. Only initializers, entity members, and entity navigation properties are supported.`

I think that's because the sort extension doesn't use expression "project.Tasks.Max(t => t.HoursEstimated)" so I tried to replace the code using schemaField.ResolveExpression and it worked.
I'm too new to this package thus wanna confirm whether the fix is good before I submit a PR.

**Comment by lukemurray** [comment]
Ahh thanks. I get it now. I think this is a test the hits the issue

```cs
[Fact]
    public void TestSortCustomField()
    {
        var schema = SchemaBuilder.FromObject<TestDataContext>();
        var data = new TestDataContext();
        data.FillWithTestData();

        schema.UpdateType<Project>(type =>
        {
            type.AddField("maxHoursEstimatedForSingleTask", project => project.Tasks.Max(t => t.HoursEstimated), "Get the max hours estimated for a single task");
        });
        schema.Query().GetField("projects", null).UseSort();
        var gql = new QueryRequest
        {
            Query =
                @"query {
                    projects(sort: [{maxHoursEstimatedForSingleTask: ASC}]) {
                        maxHoursEstimatedForSingleTask
                    }
                }",
        };

        var result = schema.ExecuteRequestWithContext(gql, data, null, null);
        Assert.Null(result.Errors);

        dynamic projects = result.Data["projects"];
    }
```

The fix you suggest is part of the solution. But I believe the other part is `UseSort` creates a `ProjectSortInput` type in the schema with the fields from the dotnet type `Project` not from the schema type `Project`. This is in `MakeSortType` in `SortExtension`.

**Comment by lukemurray** [comment]
See the PR #374 which adds an option to do that. Note because it needs to build the type then it will only take what is currently in the schema for that type.

Also, because of that it doesn't make sense to have it on the attribute as when the `SchemaBuilder` is building fields it will only have the dotnet properties at that time anyway.

**Comment by wonglae** [comment]
That makes sense. Thanks for addressing the issue
