### ISSUE TITLE
how to watch inner exceptions

### ISSUE THREAD

**Issue by wonglae** [EntityGraphQL/EntityGraphQL#368]
Some exceptions raised for the custom field I added but I can't do further diagnosis unless I can watch inner exception. 
`
"Field 'xxx' - An error occurred while preparing the command definition. See the inner exception for details."`

**Comment by lukemurray** [comment]
Are can have the detail of the exception in the error result by using the [AllowedException](https://entitygraphql.github.io/docs/schema-creation/#building-a-full-schema) options.

Looking at revamping how exceptions are handled in [6.0](https://github.com/EntityGraphQL/EntityGraphQL/issues/331)
