### ISSUE TITLE
Wildcard search for a columnvalue

### ISSUE THREAD

**Issue by santhidhanuskodi23** [EntityGraphQL/EntityGraphQL#369]
Hi,

I want to query a table with filters as column value with like condition(wildcard search with *)

something like this
query {
  products (filter: "clientCode like 'test123*'"){
    items {
      clientCode
    }
  }
}

....how can I do wildcard search? is that already supported or not?

**Comment by lukemurray** [comment]
You can use the `startsWith`, `endsWith` and `contains` methods, which is like `test123*`, `*test1223` & `*test123*`.

```
query {
  products (filter: "clientCode.startsWith(\"test123\")"){
    items {
      clientCode
    }
  }
}
```
