### ISSUE TITLE
504 Gateway Time - out

### ISSUE THREAD

**Issue by santhidhanuskodi23** [EntityGraphQL/EntityGraphQL#371]
Hi,

I am facing timeout issue in my graphql application. The .net application is deployed in AKS and configured in API Management service.
Please help me to identify the cause and fix this.

**Comment by lukemurray** [comment]
Closing as there is not enough information for me to help and it could likely be the configuration of your infrastructure. If you find it Is this library and can provide more information, please share and re open.
