### ISSUE TITLE
Multiple SQL Connections in Graph QL

### ISSUE THREAD

**Issue by santhidhanuskodi23** [EntityGraphQL/EntityGraphQL#373]
Hi,

I have developed a graph ql application using entitygraph ql. Currently it points to DEV server.
If I wnat to access UAT or Prod server for the same without creating a new application, is that possible?
User can have a drop down to select the environment or any other implementation suggestions?
Moreover this app is deployed in aks and accessed in azure api managemet portal.

**Comment by lukemurray** [comment]
I might need more information to help.

You build an API with EntityGraphQL - which is a server side "thing". If it is pointing to a dev DB and you want to control where it points to, that is out of the scope of this library. But you can dynamically create DB connections (unrelated to this library) but if the schema differs you may have issues.

If it is more that you want the front end to hit a dev/uat/prod graphql endpoint, then again that is out of the scope of this library, you would have each deployed and have you frontend choose where to post gql operations.

can you provide any more details?

**Comment by santhidhanuskodi23** [comment]
Thanks
