### ISSUE TITLE
Filter isAny([]) not working as expected

### ISSUE THREAD

**Issue by RicardoTavares16** [EntityGraphQL/EntityGraphQL#383]
Hello,

I'm trying to use the isAny([]) filter but can't seem to get it to work.

I've checked the example in the documentation 
https://entitygraphql.github.io/docs/field-extensions/filtering/
but to no avail.

I can use other different filters with no issues.

With this example query:
`{
    products(filter: "name.isAny(\"test1\", \"test2\")")
    {
        items {
                id,
                name
            }
    }
}`

I get this error:
`Errors:
[message, Method 'isAny' expects 1 argument(s) but 2 were supplied]`

If I just pass one argument:
`{
    products(filter: "name.isAny(\"test1\")")
    {
        items {
                id,
                name
            }
    }
}`

I get:
`Errors:
[message, Could not get element type from enumerable/array]`

The project is in .NET 8 and I'm using the latest version of the package (5.4.0)

**Comment by lukemurray** [comment]
Sorry the example is wrong. You need to pass an array by using `[]`

`{ products(filter: "name.isAny([\"test1\", \"test2\"])") { items { id, name } } }`

**Comment by RicardoTavares16** [comment]
That was it! 
Was going to edit the documentation but I've seen you've already did it.

Thank you
