### ISSUE TITLE
Dynamic connection String

### ISSUE THREAD

**Issue by santhidhanuskodi23** [EntityGraphQL/EntityGraphQL#384]
Hi,

Is it possible to have a dynamic connection string for entitygraphql? I want to connect to two different databases say A1 and B1 Dbs, The models are same for both dbs. I would like this db name to be passed somehow and read that value and use connection string accordingly. I can maintain multiple connection strings for the same in config json file.

But my question is that how can we pass this value in entitygraphql? I would like to pass it as a header or within body.
If there are alternative ways also, please help on that.

**Comment by lukemurray** [comment]
EntityGraphQL doesn't do the connection to the DB. It just builds expressions against an object graph, which can be a EntityFramework context.

You will have to work with EF and ASP.NET to solve this.

You will likely need to implement the controller [yourself](https://entitygraphql.github.io/docs/getting-started#executing-a-query-in-a-custom-controller) and resolve the right EntityGraphQL or context based on a header etc.

```cs
[Route("graphql")]
public class QueryController : Controller
{
    [HttpPost]
    public async Task<object> Post([FromBody]QueryRequest query, [FromServices]IServiceProvider serviceProvider, [FromServices]ISchemaProvider<MyBaseContext> schemaProvider)
    {
        var dbContext = serviceProvider.... // read header and figure out the right DbContext to fetch.
        var results = await schemaProvider.ExecuteRequestWithContextAsync(query, dbContext, HttpContext.RequestServices, null);
        // gql compile errors show up in results.Errors
        return results;
    }
}
```

you could register 2 DbContexts each set up for different connections and 1 schema provider or register 2 schema providers for each DB context/connection and look that up.

There may be a better/different way to dynamically change connection strings in asp.net but I do not know and it sits outside this library.

**Comment by santhidhanuskodi23** [comment]
Hi,

I am looking for an answer how we can pass the database name while executing this app. WE have only API body which will accpet query{}....I am looking for an option to send the value through header or body or some other ways....

If we pass through header, whats the format,...and how can we read the header value in code.

**Comment by bzbetty** [comment]
If you use the default endpoint the dbcontext is created via dependency injection, this means you can basically register a custom factory to create your dbcontext for you reading any value you like.

eg it's pretty normal to do something like this

```
    services.AddDbContext<ApplicationDbContext>(options => options.UseSqlServer("name=ConnectionStrings:DefaultConnection"));
```

you could set the connection string to anything you have access to in that scope.

you could also register a dbcontextfactory instead

```
public class DbContextFactory : IDbContextFactory<DbContext>
{
    private readonly IServiceProvider provider;

    public DbContextFactory(IServiceProvider provider)
    {
        this.provider = provider;
    }

    public DbContext CreateDbContext()
    {
        if (provider == null)
        {
            throw new InvalidOperationException($"You must configure an instance of IServiceProvider");
        }
       
      var httpContextAccessor = provider.GetService<IHttpContextAccessor>();

    var headerIfno =  httpContextAccessor.HttpContext.Request.Headers["blah"]
        return new DbContext(headerInfo);
    }
}

```

essentially it's an EFCore/ASP.NET iss you're facing not an EntityGraphQL one.

https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/

**Comment by santhidhanuskodi23** [comment]
Its not an issue. I am checking if there is an option within the API to pass connection string information like db name.
While querying the API, if i can pass the db name i body or header, Is that possible??

Or If we can have differernt end points say https://<domain>:8080/graphql/A1 or https://<domain>:8080/graphql/B1....If I have different end points, how can I read A1 and B1 and set my connection string accordingly.

**Comment by lukemurray** [comment]
This library never sees the connection string - you have to do similar to the above suggestions.

If you passed it in the GraphQL query it would be too late - the DbContext needs to be resolved. So your only options are in the request HTTP headers as above or you can have 2 endpoints and resolve the DbContext based on those.
