### ISSUE TITLE
Nested Object for Sort input

### ISSUE THREAD

**Issue by charleshoangms** [EntityGraphQL/EntityGraphQL#388]
I have an entity and association with the graphql schema 
type Entity {
  name: String
}

type Association {
  id: Int
  entity: Entity
}

I would like to sort in a query for association by the entity.businessName like 
{
  association(sort: [{ entity.name: ASC }]) {
    entity
  }
}

Is there a solution currently to sort the name inside of association that is nested because currently the SortInput does not include entity

input QueryAssociationsSortInput {
  id: SortDirectionEnum
}

**Comment by lukemurray** [comment]
From the changeling - I need to update docs - you should be able to define you're own

- #362 - The Sort field extension now supports defining more complex sort expressions that will be used. E.g.

```cs
schema.Type<TestDataContext>().GetField("people", null)
  .UseSort((Person person) => new
  {
    // [{managerName: ASC}] in GQL can be used and the full expression person.Manager.Name will be used in the OrderBy()
    managerName = person.Manager.Name,
  });
```
