### ISSUE TITLE
Querying using postman/rest api extensions

### ISSUE THREAD

**Issue by santhidhanuskodi23** [EntityGraphQL/EntityGraphQL#389]
Hi,

I have to test the graphql application locally. As this entity graphql doesnt have any UI to generate query and test, I ahve to write the query manaully.
below is one example
{
"query": "query { clients(filter: \"clientCode == \"006  \" && mediaCode == 4\")  { items {action } } }"
}
this query doesnt work at all, because of syntax issue. I have to escape with backslash the double quotes, and I cannt add additonal fields in items with this....
Please help me how I cantest this locally.

**Comment by lukemurray** [comment]
Less about this library about more about how to have strings inside strings in JSON. To make this easier you could use variables so you only have 1 level of escaping.

```json
{
    "query": "query MyQuery($filter: String!) { clients(filter: $filter && mediaCode == 4") { items {action } } }",
    "variables": {
        "filter": "clientCode == \"006\""
    }
}
```

Also Postman has a GraphQL option that allows you to write only the graphql parts not the raw json. I think you have to sign in to an account for it though.
