### ISSUE TITLE
Generate Schema.Graphql

### ISSUE THREAD

**Issue by santhidhanuskodi23** [EntityGraphQL/EntityGraphQL#390]
Hi,

I would like to know how I can generate schema.graphql automatically in my .net core using entity graphql.

**Comment by lukemurray** [comment]
Depending on your requirements you can generate it on startup by calling `var schemaString = schema.ToGraphQLSchemaString();` and writing that string to a file.

Or you could go a step further and have a project that uses the schema and outputs it and add it to your build step in another project e.g.

```
  <Target
    Name="GenerateGraphQLFiles"
    BeforeTargets="AfterBuild"
  >
    <Exec Command="dotnet run --project &quot;$(ProjectDir)/MyGenerator/Generator.csproj&quot; "/>
  </Target>
```

The library doesn't provide anything itself apart from the ability to get the schema string. You should be able to use any of your build tooling to generate it when you need.

**Comment by santhidhanuskodi23** [comment]
Any other tools available for this?
Visual studio package and tools? can you elloborate on other options please.

**Comment by lukemurray** [comment]
No. This library does not provide another library that generates it for you. You need to use this library in some part of your build process. I don’t know what your build process is.

The dotnet build tools make it easy to execute code.

What are you trying to achieve?
________________________________

**Comment by santhidhanuskodi23** [comment]
I know this library does not provide. I am just requesting you to assist to generate schema.graphql easily in my .net core application which is using entitygraphql.
you mentioned  var schemaString = schema.ToGraphQLSchemaString();...but what is schema here? how do we initialize schema?

**Comment by lukemurray** [comment]
Assuming you have set EntityGraphQL up using `EntityGraphQL.AspNet` and have this somewhere in your startup

```cs
services.AddGraphQLSchema<MyContext>();
```

You could use the `ConfigureSchema` callback in the options to output the schema.


```cs
services.AddGraphQLSchema<MyContext>(options => {
    options.ConfigureSchema = (gqlSchema) => {
        // do any customisation of the schema here if you need

        var schemaStr = gqlSchema.ToGraphQLSchemaString();
        File.WriteAllText("schema.graphql", schemaStr);
    };
});
```

This will save the schema once on each app start. I hope that helps.
