### ISSUE TITLE
Crash on nested null IEnumerable

### ISSUE THREAD

**Issue by agenceplus-emillon** [EntityGraphQL/EntityGraphQL#392]
On a resolver returning a collection of objects containing nested collections of object, the query raise an ArgumentNullException if a property value is null and queried on.

Example:
```C#
class Text {
  public string Value { get; set; }
}
class Result {
  public IEnumerable<Text>? Texts { get; set; }
}
```
From debugging in the stack trace it appears the generated dynamic expression is something like that:
results.SelectWithNullCheck(r => r.Texts.Select(t => t.Value))

This need to generate instead:
results.SelectWithNullCheck(r => r.Texts.SelectWithNullCheck(t => t.Value))

**Comment by lukemurray** [comment]
`SelectWithNullCheck` will fail with EF is using against a `DbContext` (which this library aims to support well without having it as a dependency. I assume you are executing against an in-memory object?

**Comment by agenceplus-emillon** [comment]
Yes, it is executed against an in-memory object.

**Comment by lukemurray** [comment]
Latest change in master adds better null checking for when `ExecuteServiceFieldsSeparately` is `false` (or when it includes service fields) which you should use if you are not querying against a EF `DbContext`.

Let me know if there are any more issues you encounter.

**Comment by agenceplus-emillon** [comment]
Thanks you, I no longer have exceptions with null collections.

Note: if someone search how to set ExecuteServiceFieldsSeparately with AspNet without a custom controller:
```csharp
app.MapGraphQL<GraphqlContext>(options: new ExecutionOptions
{
    ExecuteServiceFieldsSeparately = false
});
```
