### ISSUE TITLE
What's the difference between this and Hot chocolate?

### ISSUE THREAD

**Issue by iqoOopi** [EntityGraphQL/EntityGraphQL#394]
We have a .net backend doing CRUD with EF core. Wondering what's the difference between this package vs hot chocolate? 

Any advantages/disadvantages?

One advantage I can see is that seems like you don't need to define any query once you hook up with EF core, anything else?

**Comment by lukemurray** [comment]
Honestly, I haven't looked at Hot Chocolate in detail for a long time. And I have never used it in a project. 

Ages ago when this library was started one focus was how it generated an expression for the whole GraphQL query and executes that in a way that would work well EF. Meaning it only fetches (using `Select()` the fields requested from the DB, not the whole row. While also being able to extend the schema for other data sources.

At this point I'm sure there are a lot of similarities in functionality with different interfaces and implementation details.

Is there something you're looking to do that Hot Chocolate can't or that this library can't?
