### ISSUE TITLE
DataType and DAta values Issues

### ISSUE THREAD

**Issue by santhidhanuskodi23** [EntityGraphQL/EntityGraphQL#395]
Hi,

I noticed below issues in entity graph ql
- When the data is null in the source, the column is not returned in the query result 
-When source column type is Bit(1 or 0),  the column values are returned  true or false in graphql

Is this expected behaviour? How do we fix this, if not?

**Comment by lukemurray** [comment]
Can you expand on the first point about `null` ? This is likely how the JSON serialiser is handling it.

`Bit` again is likely the JSON serialiser. You can register a custom type converter with this library to return a number (assume you want that) - this gives an example - https://entitygraphql.github.io/docs/serialization-naming/newtonsoft-json/

Or you could likely do similar with the JOSN serialiser.

**Comment by santhidhanuskodi23** [comment]
Ok Thanks,
I would like to get detailed info on implementing the fix that you suggested.
My application is a simple .net core using entitygraphql library. I have my code in startup.cs in ConfigureServices(0 methd


 
   services.AddHttpContextAccessor();

  // Register MediaDBContext with IHttpContextAccessor
  services.AddDbContext<MediaDBContext>((serviceProvider, options) =>
  {
      var httpContextAccessor = serviceProvider.GetRequiredService<IHttpContextAccessor>();
      var connection = new SqlConnection(GetConnectionString(httpContextAccessor));

      var creds = new Azure.Identity.DefaultAzureCredential();
      var token = creds.GetToken(new Azure.Core.TokenRequestContext(new[] { "https://database.windows.net/.default" }));
      connection.AccessToken = token.Token;

      options.UseSqlServer(connection);
  });
  
   services.AddGraphQLSchema<MediaDBContext>(provider =>
 {
     provider.OnFieldCreated = (field) =>
     {
         if (field.ReturnType.IsList && field.ReturnType.SchemaType.GqlType == GqlTypes.QueryObject && !field.FromType.IsInterface)
         {
             field.UseFilter().UseSort().UseOffsetPaging(defaultPageSize: DefaultPageSize, maxPageSize: MaxPages);
         }
     };
 });

I  am not having any other custom classes to implement any variations. I have MediaDBContext file and all other model files.
I am not sure where this fix that you propsed for jsonconvert will be fitting, How I can change my current code, where will this new code goes in?


 
   services.AddHttpContextAccessor();

  // Register MediaDBContext with IHttpContextAccessor
  services.AddDbContext<MediaDBContext>((serviceProvider, options) =>
  {
      var httpContextAccessor = serviceProvider.GetRequiredService<IHttpContextAccessor>();
      var connection = new SqlConnection(GetConnectionString(httpContextAccessor));

      var creds = new Azure.Identity.DefaultAzureCredential();
      var token = creds.GetToken(new Azure.Core.TokenRequestContext(new[] { "https://database.windows.net/.default" }));
      connection.AccessToken = token.Token;

      options.UseSqlServer(connection);
  });
  
   services.AddGraphQLSchema<MediaDBContext>(provider =>
 {
     provider.OnFieldCreated = (field) =>
     {
         if (field.ReturnType.IsList && field.ReturnType.SchemaType.GqlType == GqlTypes.QueryObject && !field.FromType.IsInterface)
         {
             field.UseFilter().UseSort().UseOffsetPaging(defaultPageSize: DefaultPageSize, maxPageSize: MaxPages);
         }
     };
 });

**Comment by santhidhanuskodi23** [comment]
Can you expand on the first point about null ? This is likely how the JSON serialiser is handling it.

When the source value contains null for a specific column, when I query the table for n number of columns, it returns only the columns which do not contain null values, It doesnt even show that column name in the output for those null values

**Comment by santhidhanuskodi23** [comment]
I have implemented the custom controller as in doc and added JSON options to configureservices() mehod. But Still it is not working.

**Comment by bzbetty** [comment]
I suspect this is something RuntimeTypeJsonConverter is doing (excluding nulls). 

Can you show your custom controller implementation?

**Comment by lukemurray** [comment]
Have you changed the `DefaultIgnoreCondition`? https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.defaultignorecondition?view=net-5.0

**Comment by lukemurray** [comment]
5.4.3 fixed the `null` issue described here. The serialisation of `Bit` will be up to the json serialisation library.
