### ISSUE TITLE
IN Condition Support

### ISSUE THREAD

**Issue by santhidhanuskodi23** [EntityGraphQL/EntityGraphQL#401]
Hi, 

I would like to add multiple values in filter condition with 'IN' operator similar to SQL. Is that supported?
What is the syntax for the same?

My req is to query clients 'A', 'B', 'C', 'D' etc....I can pass n number of values. With current filter support, it is allowed to provide multiple equal conditions joined with AND , OR operators. But this is not a ideal solution. 

Looking for suggestions.

**Comment by bzbetty** [comment]
Do you mean something like this https://github.com/EntityGraphQL/EntityGraphQL/issues/383

**Comment by lukemurray** [comment]
Sorry, we'll need some more details. You can add the filter extension to fields and use `isAny` and you can read more here https://entitygraphql.github.io/docs/field-extensions/filtering
