### ISSUE TITLE
Correct usage of .where() filter

### ISSUE THREAD

**Issue by RicardoTavares16** [EntityGraphQL/EntityGraphQL#404]
Hello,

I'm trying to use the .where() filter

I have a schema "product" with multiple "productSpecificationAttributes"

but when I try to filter the "product" by properties of the "productSpecificationAttributes" using .where() I get an error

this query 

```
{
    products(filter: "productSpecificationAttributes.where(customValue == \"Test\")")
    {
        items {
                id,
                name,
                productSpecificationAttributes {
                    customValue
                }
                
            }
    }
}
```

returns the error

[message, Object of type 'System.Linq.Expressions.Expression1`1[System.Func`2[Repository.Entities.Products.Products.Product,System.Collections.Generic.IEnumerable`1[Repository.Entities.Products.Products.ProductSpecificationAttribute]]]' cannot be converted to type 'System.Linq.Expressions.Expression`1[System.Func`2[Repository.Entities.Products.Products.Product,System.Boolean]]'.]

Am I doing something wrong in the query?

**Comment by jarmanso7** [comment]
Same doubt here

**Comment by lukemurray** [comment]
How is `customValue` defined?

Oh actually this is likely related to having paging on as well. Which means it is the same as #378

**Comment by RicardoTavares16** [comment]
> Same doubt here. For what is worth, check if any() works for your use case:
> 
> ```
> {
>     products(filter: "productSpecificationAttributes.any(customValue == \"Test\")")
>     {
>         items {
>                 id,
>                 name,
>                 productSpecificationAttributes {
>                     customValue
>                 }
>                 
>             }
>     }
> }
> ```

It can work to give me the Products that have ProductSpecificationAttributes matching the condition, but not if I want only the list of ProductSpecificationAttributes filtered by the condition

**Comment by RicardoTavares16** [comment]
> How is `customValue` defined?
> 
> Oh actually this is likely related to having paging on as well. Which means it is the same as #378

The product class has a collection of ProductSpecificationAttributes

`public virtual ICollection<ProductSpecificationAttribute> ProductSpecificationAttributes { get; set; }`

and a ProductSpecificationAttribute has a string property called CustomValue

`public string CustomValue { get; set; }`

the Product schema is declared like this 

```
schema.Query().AddField("products", "List of products")
.Resolve(ctx => ctx.Product)
.UseFilter()
.UseSort()
.UseOffsetPaging();
```
    
but I also tried without the UseSort() and UseOffsetPaging() and got the same result, so I don't think this is related with pagination... could you give an example of a correct usage of the .where() filter? I don't see any example in the documentation, maybe I'm declaring it wrong.

**Comment by lukemurray** [comment]
If I add this test in `FilterExtensionTests`

```cs
[Fact]
    public void SupportUseFilterAnyMethodOnCollection()
    {
        var schema = SchemaBuilder.FromObject<TestDataContext2>();
        var gql = new QueryRequest
        {
            Query =
                @"query Query($filter: String!) {
                    people(filter: $filter) { id name }
                }",
            Variables = new QueryVariables { { "filter", "taskCollection.any(name == \"Home\")" } }
        };
        var data = new TestDataContext2().FillWithTestData();
        data.People.Add(DataFiller.MakePerson(33, null, null));
        data.People.Add(DataFiller.MakePerson(33, null, null));
        data.People.First().Name = "Lisa";
        data.People.First().TaskCollection.Add(new Task { Name = "Home" });
        var tree = schema.ExecuteRequestWithContext(gql, data, null, null);
        Assert.Null(tree.Errors);
        dynamic people = ((IDictionary<string, object>)tree.Data)["people"];
        Assert.Equal(1, Enumerable.Count(people));
        var person = Enumerable.First(people);
        Assert.Equal("Lisa", person.name);
    }
```
And add `taskCollection` to the test `Person` type

```cs
public virtual ICollection<Task> TaskCollection { get; set; } = [];
```

This passes for me.

Are you able to make a test that fails?

How are you sending the query? Is it messy up the string?. What if you use variables in the request?

```json
// full JSON requests 
{
  "query": "query MyQuery($filter: String!) {
    products(filter: $filter)
    {
        items {
                id,
                name,
                productSpecificationAttributes {
                    customValue
                }
                
            }
    }
}",
  "variables": {
    "filter": "productSpecificationAttributes.where(customValue == \"Test\")"
  }
}
```

**Comment by lukemurray** [comment]
Closing unless we can get more information of reproducing the issue.
