### ISSUE TITLE
How can I use Middleware?

### ISSUE THREAD

**Issue by ug-code** [EntityGraphQL/EntityGraphQL#417]
I am currently using EntityGraphQL with .NET 6.
I would like to set up a middleware structure in my project. I reviewed the documentation, but I couldn’t find how to do this.

We are using JWT, and we have different validations for requests. I would like to use middleware to handle these validations in between. How can I achieve this?

Thank you in advance for your response.

**Comment by lukemurray** [comment]
EntityGraphQL isn't a web sever itself. Assuming you are using ASP.NET, you can follow its docs and tutorials to add JWT auth etc. 

`MapGraphQL` just adds a middleware to handle the URL endpoint. It will be author etc if you turn that on with the dotnet `UseAuthentication` and `UseAuthorization` middleware.

Is there something more specific you are having issues with?

**Comment by ug-code** [comment]
Thank you for your help. I have resolved the issue; we can close it now
