### ISSUE TITLE
UpdateCollectionNodeFieldExpression modifies CollectionSelectionNode

### ISSUE THREAD

**Issue by bzbetty** [EntityGraphQL/EntityGraphQL#418]
I'm still back on 5.2.0, so might not be an issue in the current version - although a quick scan of the code I don't see anything that would fix it.

Noticed when an expression uses FirstOrDefault (and presumably a number of other methods) it gets converted to a where statement.

Unfortunately it seems to append this where statement every time the query is executed as it's modifying CollectionSelectionNode.ListExpression directly, which means after every run it has an extra Where statement appended and thus makes a unique expressiontree every time through, thus missing out on EF compile cache, SQL plan cache and any other caching one might have enabled.

**Comment by lukemurray** [comment]
OK this is interesting. I haven't really thought about the EF caching features. If it doesn't take this library depending on EF I'm all for making it work better with it.

Is it only `FirstOrDefault` style fields? As it builds a full expression every time as well.

**Comment by bzbetty** [comment]
It'll be any of the methods in this hashset

```
 public static readonly HashSet<Tuple<Type, string>> ListToSingleMethods =
 [
     Tuple.Create(typeof(Enumerable), nameof(Enumerable.First)),
     Tuple.Create(typeof(Enumerable), nameof(Enumerable.FirstOrDefault)),
     Tuple.Create(typeof(Enumerable), nameof(Enumerable.Last)),
     Tuple.Create(typeof(Enumerable), nameof(Enumerable.LastOrDefault)),
     Tuple.Create(typeof(Enumerable), nameof(Enumerable.Single)),
     Tuple.Create(typeof(Enumerable), nameof(Enumerable.SingleOrDefault)),
     Tuple.Create(typeof(Queryable), nameof(Queryable.First)),
     Tuple.Create(typeof(Queryable), nameof(Queryable.FirstOrDefault)),
     Tuple.Create(typeof(Queryable), nameof(Queryable.Last)),
     Tuple.Create(typeof(Queryable), nameof(Queryable.LastOrDefault)),
     Tuple.Create(typeof(Queryable), nameof(Queryable.Single)),
     Tuple.Create(typeof(Queryable), nameof(Queryable.SingleOrDefault)),
 ];
```

as that's what this method is using

```
  public static string? UpdateCollectionNodeFieldExpression(GraphQLListSelectionField collectionSelectionNode, Expression combineExpression)
  {
      string? capMethod = null;
      if (combineExpression.NodeType == ExpressionType.Call)
      {
          // In the case of a First() we need to insert that select before the first
          // This is all to have 1 nice expression that can work with ORMs (like EF)
          // E.g  we want db => db.Entity.Select(e => new {name = e.Name, ...}).First(filter)
          // we dot not want db => new {name = db.Entity.First(filter).Name, ...})

          var call = (MethodCallExpression)combineExpression;
          if (ListToSingleMethods.Contains(Tuple.Create(call.Method.DeclaringType!, call.Method.Name)))
          {
              // Get the expression that we can add the Select() too
              var contextExpression = collectionSelectionNode.ListExpression;
              if (contextExpression != null && call.Arguments.Count == 2)
              {
                  // this is a ctx.Something.First(f => ...)
                  // move the filter to a Where call so we can use .Select() to get the fields requested
                  var filter = call.Arguments.ElementAt(1);
                  var isQueryable = typeof(IQueryable).IsAssignableFrom(contextExpression.Type);
                  contextExpression = isQueryable
                      ? MakeCallOnQueryable(nameof(Queryable.Where), [combineExpression.Type], contextExpression, filter)
                      : MakeCallOnEnumerable(nameof(Enumerable.Where), [combineExpression.Type], contextExpression, filter);
                  // we can first call ToList() as the data is filtered so risk of over fetching is low
                  capMethod = call.Method.Name;
                  collectionSelectionNode.ListExpression = contextExpression;
              }
          }
      }
      return capMethod;
  }
```

I suspect the problem is as simple as the check is being done on the combineExpression, but the collectionSelectionNode.ListExpression is the one being modified.  So thus it modifies the same expression over and over every time it goes through the method.

So either UpdateCollectionNodeFieldExpression shouldnt' be called multiple times, or it needs a flag (or other way) to check if it's already been run.

My suspicion is you could probably just do it in the constructor.

**Comment by lukemurray** [comment]
Thanks for that info. Do you know an easy way to confirm that EF is using it's cache?

**Comment by bzbetty** [comment]
As long as it's not unique it should be a cache hit.

However there are event counters which expose the info.
https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/metrics?tabs=windows

**Comment by lukemurray** [comment]
See https://github.com/EntityGraphQL/EntityGraphQL/blob/master/src/tests/EntityGraphQL.EF.Tests/EFCacheTests.cs

It appears the cache is being used. Not sure if you have a better way to reproduce the issue?

**Comment by bzbetty** [comment]
In TestEfCoreQueryCacheWithListToSingleNode add this

   schema.UpdateType<Actor>(c =>
        {
            c.ReplaceField("movie", new { id = 0 }, (c, args) => c.Movies.FirstOrDefault(x => x.Id == args.id), "");
        });

**Comment by lukemurray** [comment]
Thanks! Odd as that is what SchemaBuilder builds!
