### ISSUE TITLE
Filter IsAny not wokring in Int Type

### ISSUE THREAD

**Issue by shantidhanus82** [EntityGraphQL/EntityGraphQL#419]
Hi,

Query Filter 'IsAny' not working in integer datatype.

The below query is not working nad it throws error
                query {
                    clients(filter: "Code.isAny[5,2,3,10,11,12]") {
                        items {
                Code
                        }
                    }
                }

**{
  "errors": [
    {
      "message": "Field 'isAny' not found on type 'Int'"
    }
  ]
}**

**Comment by lukemurray** [comment]
You need to call it like a method `Code.isAny([5,2,3,10,11,12])"` note the brackets

**Comment by shantidhanus82** [comment]
It is not working even with the brackets. It throws below error
Wat is the limitation of isAny? Does it support all data types? why it throws below error?

{
  "errors": [
    {
      "message": "Method 'isAny' not found on current context 'Nullable`1'"
    }
  ]
}
