### ISSUE TITLE
Cursor pagination with 'last' and 'before'

### ISSUE THREAD

**Issue by BRUS1NATOR** [EntityGraphQL/EntityGraphQL#427]
I had unexpected results on my frontend app when I have tried to paginate backward.
I'm using the demo project to reproduce this issue. 
Considering data:
![image](https://github.com/user-attachments/assets/1bc38da6-ff5c-4f99-aedb-fda704a603d0)
When paginating forward I get endcursor with value "Mg==" which is expected.
![image](https://github.com/user-attachments/assets/7c8f9a06-27c7-49d6-92a2-939d6f124edb)
Then try to get previous node with arguments (last:1, before: "Mg==") and expecting to get entity with id = 1. As you can see I get correct node with previous cursor "MQ==", but id of entity is incorrect.
![image](https://github.com/user-attachments/assets/1fba9b5b-32a7-433a-9ca4-7c67884c41b7)
If I try to get 2 entities instead of 1, the returned cursors are kinda "shifted". Entity with id=1 has cursor "MA==".
![image](https://github.com/user-attachments/assets/b09ad613-60f4-4812-b7f0-d522c33d21fa)

I think it has something to do with cursor computation when using 'last' argument.

**Comment by elliotwannemacher-insource** [comment]
I put up pr #428 to fix this.

If you need a solution in the meantime, I can send the custom field extension code I've been using as a workaround.
