### ISSUE TITLE
Maximum response time

### ISSUE THREAD

**Issue by santhidhanuskodi23** [EntityGraphQL/EntityGraphQL#434]
Hi,

GraphQL is timing out and giving error "504 Gateway Time - out". How do I increase the timeout period?

Below is my code
 services.AddGraphQLSchema<TestDBContext>(provider =>
 {
     provider.OnFieldCreated = (field) =>
     {
         if (field.ReturnType.IsList && field.ReturnType.SchemaType.GqlType == GqlTypes.QueryObject && !field.FromType.IsInterface)
         {
             field.UseFilter().UseSort().UseOffsetPaging(defaultPageSize: DefaultPageSize, maxPageSize: MaxPages);
         }
     };
 });

**Comment by lukemurray** [comment]
Given it is just ASP.net you can set timeout at the web server level https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/options?view=aspnetcore-9.0 or the endpoints (https://learn.microsoft.com/en-us/aspnet/core/performance/timeouts?view=aspnetcore-9.0 and below example)

```
endpoints.MapGraphQL<DemoContext>(
                configureEndpoint: endpoint =>
                {
                    endpoint.WithRequestTimeout(TimeSpan.FromSeconds(2));
                }
            );
```

**Comment by santhidhanuskodi23** [comment]
This is not working. withREqestTimeoutmethod is not known....

**Comment by santhidhanuskodi23** [comment]
Could you please respond?

**Comment by lukemurray** [comment]
What version of dotnet are you using?

These are dotnet features not EntityGraphQL. That `configureEndpoint` callback lets you configure the APS.NET endpoint that is created.

**Comment by lukemurray** [comment]
Closing unless there is something specific to EntityGraphQL you can replicate.

dotnet and ASP.NET docs should cover what you need.
