### ISSUE TITLE
Mutation Func enums

### ISSUE THREAD

**Issue by doper-147** [EntityGraphQL/EntityGraphQL#56]
I have 2 mutation methods and i have problem with calling it:

        [GraphQLMutation]
        public Expression<Func<CpiContext, Config>> AddConfig(AddConfigArgs args)
        {
            Func<CpiContext, Config> bodyFunction = db =>
            {
                CpiRepository repo = new CpiRepository(db);
                var result = repo.SaveConfigAsync(new Config()
                {
                    Name = args.Name,
                    Value = args.Value
                });
                result.Wait();
                return result.Result;
            };
            return db => bodyFunction(db);
        }

and

        [GraphQLMutation]
        public Expression<Func<CpiContext, Config>> GetEmptyInstance()
        {
            return db => new Config()
            {
            };
        }

When I browsed EntityGraphQL code, i found not implemented ExpressionType enums (ExpressionType.Invoke and ExpressionType.MemberInit) in method GraphQLMutationNode.ExecuteAsync(TContext context, GraphQLValidator validator, IServiceProvider serviceProvider). 

Is it possible to add resolving for those enums? Thank you.

**Comment by lukemurray** [comment]
For the first one, I think we could easily support that. I'll leave this open as a reminder.

For the second one, it could likely be supported but given you are not returning an object in you schema context, you could just return the Config object as such

```c#
[GraphQLMutation]
    public Config GetEmptyInstance()
    {
        return new Config()
        {
        };
    }
```

The expression really allows it to be lazily executed against your context which could be a ORM such as EntityFramework.

**Comment by lukemurray** [comment]
Actually with the first one you do not want to do that. You mutation:

```c#
[GraphQLMutation]
    public Expression<Func<CpiContext, Config>> AddConfig(AddConfigArgs args)
    {
        Func<CpiContext, Config> bodyFunction = db =>
        {
            CpiRepository repo = new CpiRepository(db);
            var result = repo.SaveConfigAsync(new Config()
            {
                Name = args.Name,
                Value = args.Value
            });
            result.Wait();
            return result.Result;
        };
        return db => bodyFunction(db);
    }
```

If you do this GQL

```gql
mutation {
   addConfig(...) { field1 field2 }
}
```

it will generate this expression (simplifying it)

```c#
(ctx, bodyFunction) => new {
    addConfig = bodyFunction(ctx) == null ? null : new {
        field1 = bodyFunction(ctx).field1,
        field2 = bodyFunction(ctx).field2
    }
}
```

You see that it will execute the `bodyFunction` multiple times. I suggest you do something like

```c#
[GraphQLMutation]
 public Config AddConfig(AddConfigArgs args)
 {
    CpiRepository repo = new CpiRepository(db);
    var result = repo.SaveConfigAsync(new Config()
    {
        Name = args.Name,
        Value = args.Value
    });
    result.Wait();
    return result.Result;
}
```

If `Config` is part of the `CpiContext` then change the return to something like

```c#
public Expression<Func<CpiContext, Config>> AddConfig(AddConfigArgs args)
{
// ...
    return db => db.Config; // or however you select the right config
}
```

This will allow full selection through the relations (if any)

And now it will generate either
```c#
(ctx, configResult) => new {
    addConfig = configResult == null ? null : new {
        field1 = configResult.field1,
        field2 = configResult.field2
    }
}
```
or 
```c#
(ctx) => new {
    addConfig = ctx.Config == null ? null : new {
        field1 = ctx.Config.field1,
        field2 = ctx.Config.field2
    }
}
```

And the mutation work is only done one.
