### ISSUE TITLE
Authorization by custom condition

### ISSUE THREAD

**Issue by Yauheniii** [EntityGraphQL/EntityGraphQL#67]
In the ClaimsPrincipal I have a field that describes the list of rights available to authorized user:
```
public List<string> Rights {get; set;}
```
In the database I have an Organization entity that also has a set of rights.
```
public class Organization
{
      public int OrganizationId { get; set; }
        
      public ICollection<string> Rights { get; set; }
}
```
Is it possible somehow for any requests return only organizations that have at least 1 right that the user has in ClaimsPrincipal? So that I can write something like:
```
organization.Rights.Intersect(userRights).Any();
```
The client will use different search filters as well.

**Comment by AnderssonPeter** [comment]
Just a idea, but why not add a `HasAtleastOneRight` ClaimsPrincipal if the manually `Organization` has at least one right then you can use the attribute that is already provided to check for `HasAtleastOneRight`.

**Comment by Yauheniii** [comment]
What do you mean by "already provided attribute"? I only see еthe `GraphQLAuthorize `attribute which only works with `ClaimTypes.Role` claim.
I also did not quite understand about `HasAtleastOneRight ` ClaimsPrincipal. I only know the set of user rights at the time the ClaimsPrincipal is created. At this point, I don't know anything about the organizations that I want to receive from the server. I need to cut off unwanted organizations that do not have common rights with the user at the time of the GraphQL request.

**Comment by lukemurray** [comment]
upcoming 1.1 adds support for ASP.NET policy authorization which lets you do many complex checks.

But I believe you want to filter data based on a users claims - or row based authorization. You can do this before EntityGraphQL ever sees the context.

If you are using entity framework as the context you can implement `OnModelCreating` in your `DbContext` and provide filtering of organisations based on user information (you will have to set up DI correctly to get the user information where you need). Abstract example fro DbCOntext

```c#
modelBuilder.Entity<Organization>().HasQueryFilter(org =>
    userService.OrganizationId == org.Id);
```

You can read more here https://docs.microsoft.com/en-us/ef/core/querying/filters
