### ISSUE TITLE
Inconsistent usage of attributes to mark a field as not null/required?

### ISSUE THREAD

**Issue by AnderssonPeter** [EntityGraphQL/EntityGraphQL#69]
There might be a good reason for this if that is the case just close the issue!

But when marking a argument as required in some parts of this library use the `RequiredAttribute` and some parts use the `GraphQLNotNullAttribute` attribute.

I was confused why applying the `RequiredAttribute` to a field on my Entity had no effect, after looking at the source i found the `GraphQLNotNullAttribute` applying that attribute ensured that the field was marked as required.

**Comment by lukemurray** [comment]
You are right. I stupidly didn't know about/forgot about the default dotnet `RequiredAttribute`. We should deprecate `GraphQLNotNullAttribute` and use `RequiredAttribute` in its place.

**Comment by lukemurray** [comment]
Fixed in upcoming 1.1
