### ISSUE TITLE
SchemaBuilder.FromObject<T>() can not build schema from a DbContext with IDictionary property

### ISSUE THREAD

**Issue by mrvenus314** [EntityGraphQL/EntityGraphQL#72]
Here is my dbcontext:
public abstract class MultiTenantDbContext : DbContext, IMultiTenantDbContext
    {
        protected MultiTenantDbContext(TenantInfo tenantInfo);
        protected MultiTenantDbContext(TenantInfo tenantInfo, DbContextOptions options);
        public TenantInfo TenantInfo { get; }
        public TenantMismatchMode TenantMismatchMode { get; set; }
        public TenantNotSetMode TenantNotSetMode { get; set; }
        protected string ConnectionString { get; }
        public override int SaveChanges(bool acceptAllChangesOnSuccess);
        public override Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default);
        protected override void OnModelCreating(ModelBuilder modelBuilder);
    }

The object "TenantInfo" has a property which is IDictionary<string, object>   
public class TenantInfo
    {
        public TenantInfo();
        public TenantInfo(string id, string identifier, string name, string connectionString, IDictionary<string, object> items);

        public string Id { get; internal set; }
        public string Identifier { get; internal set; }
        public string Name { get; internal set; }
        public string ConnectionString { get; internal set; }
        public IDictionary<string, object> Items { get; internal set; }
        public MultiTenantContext MultiTenantContext { get; internal set; }
    }

when I run the project, class SchemaBuilder.cs will throw exciption with "Value cannot be null. (Parameter 'type')"  caused by IDictionary property

**Comment by SerialRYaya** [comment]
I'm having the same issue (2021-08-25).

In my code, I call SchemaBuilder.FromObject<MyDbContext> which dbContext has an entity with a Dictionary<string, string> property.

In SchemaBuilder.ProcessFieldOrProperty, when searching for a returnType, it gets null.

`var returnType = le.ReturnType.IsEnumerableOrArray() ? le.ReturnType.GetEnumerableOrArrayType() : le.ReturnType.GetNonNullableType();`

IsEnumerableOrArray() returns true but GetEnumerableOrArrayType() returns null. Then null is passed to the CacheType method where the exception happens.

The problem seams to come from the GetEnumerableOrArrayType() extension method. 
`            if (type == typeof(string) || type == typeof(byte[]) || type == typeof(byte))
            {
                return null;
            }
            if (type.IsArray)
                return type.GetElementType();
            if (type.GenericTypeArguments.Count() == 1)
                return type.GetGenericArguments()[0];
            return null;`

The count checking of GenericTypeArguments expects 1 argument but the Dictionary has 2 generic arguments.

**Comment by lukemurray** [comment]
Yes these currently isn't supported. I'll look at adding it (or a PR). We might support it with type mappings as GraphQL doesn't have the concept of dictionaries, so it could be a list of objects that have a key and value.

Apart from no error, what would you expect from the query side? Given the gql spec if we mapped it to a `KeyValuePair` you could query like

```gql
{
   dictionary {
      key
      value {
         ...
      }
   }
}
```

Or if you want to ignore that field use `[GraphQLIgnore]`

**Comment by SerialRYaya** [comment]
Thank you very much Luke!
I was wondering how I could do to convert the Dictionary to a string (with serialization) but since I don't need to query these specific fields with GraphQL, I'll use [GraphQLIgnore].
That said, I believe that what you suggest would be a nice feature.
