### ISSUE TITLE
Do not  use this project !

### ISSUE THREAD

**Issue by shikiiGithub** [EntityGraphQL/EntityGraphQL#85]
Everyone who sees this project please do not use it !  It has so many bugs that you will waste your time . Value you time please !

**Comment by lukemurray** [comment]
This isn't helpful at all. You're free not to use it. But if you do encounter a bug I'd love for you to actually create an issue that describes the bug you found. Also how you are using it (against an EF context or not).

Then the bugs can actually be fixed.
