### ISSUE TITLE
Not working Mutation Authorization

### ISSUE THREAD

**Issue by klimovmk0** [EntityGraphQL/EntityGraphQL#86]
Hello. I'am use GraphQLAuthorize for MutationFunction and authorization doesn't work. ( See Screen)
![image](https://user-images.githubusercontent.com/96753726/147515416-3e53ff74-53c6-4a8a-8e95-c1be863cce31.png)
I decided to download your project and debug it. After debugging, I came to the conclusion that authorization does not work for mutations. Maybe I'm wrong, if that's the case, tell me what could be the problem. I also made edits in the local git, maybe this will help (screen below)
![image](https://user-images.githubusercontent.com/96753726/147515546-4a465a85-a607-470b-996e-7be2b277ea20.png)
![image](https://user-images.githubusercontent.com/96753726/147515559-87f57543-ebbf-4b46-9c04-2aaa01e66a4f.png)

**Comment by lukemurray** [comment]
Thanks. I have just pushed version 1.0.3 to nuget.

Note the check you removed is still there. It checks that the user has access to the Type returned by the mutation (or field) as you can secure types as well.
