### ISSUE TITLE
Remove Newsoft.Json dependency

### ISSUE THREAD

**Issue by asinino** [EntityGraphQL/EntityGraphQL#89]
Hello

Now that the dependency was removed from the code can we remove it from the project dependencies?
Based on Pull Request #1 

Also can not find any call to this library on the main project, only for testing but that is not distributable.

**Comment by lukemurray** [comment]
Currently it is used in `ExpressionUtil.cs` to support variable objects that nested objects in them as they will come through as `Newtonsoft.Json.Linq.JToken` or `Newtonsoft.Json.Linq.JObject`.

I agree I would like to remove it completely so open to idea for how to best support that.

Can I ask the issue it is causing you?
