### ISSUE TITLE
Implement GraphQL subscriptions

### ISSUE THREAD

**Issue by lukemurray** [EntityGraphQL/EntityGraphQL#9]

**Comment by patty-caked** [comment]
Hi. I'm still somewhat new to dealing with GraphQL, EntityFramework and .NET Core web APIs in general (1.5 months since knowing literally nothing), and your project has helped speed up and automate development significantly, since I'm working with an existing database with hundreds of tables and thousands of fields.
But I was hoping to add subscription capabilities to this project too. I know enough about subscriptions to get them working in a smaller vanilla GraphQL project **_without_** this repo, but I'm unsure of where to begin with my main project that **_does_** use this repo.

Could I get some help or any pointers on where to start with this?

**Comment by lukemurray** [comment]
How would you implement it without this repo? With another library?

I haven't really looked into this yet. But I assume we'll need some pub/sub or signalr implementation. I'd be interested to see how client libraries like Apollo expect subscriptions to work.

**Comment by JTravis76** [comment]
Subscriptions are real-time communication between client and server. Like notification or chat services. Guessing you would need to start with web sockets or something similar.

**Comment by patty-caked** [comment]
> How would you implement it without this repo? With another library?
> 
> I haven't really looked into this yet. But I assume we'll need some pub/sub or signalr implementation. I'd be interested to see how client libraries like Apollo expect subscriptions to work.

As far as I can tell, a large portion of the work is done by [websocket stuff from GraphQL.Server](https://github.com/graphql-dotnet/server) as well as the websocket middleware extension in the Microsoft.AspNetCore.App nuget package.

What I have to actually set up in my little "vanilla" graphql test project is:
- A database context for an in-memory testing database.
- A few models for said database.
- Define the query, mutation, and subscription classes and methods with proper attributes for them.
- A class that generates a GraphQL.Types.ISchema object from a string of type definitions and these three classes.

And the last thing I had to do specifically for Subscriptions was to make this class, and make a singleton for it so I can access it in subscription methods and mutation methods. 
```
using System.Reactive.Linq;
using System.Reactive.Subjects;

public class SubItem
{
    // Stores the most recent element to be added to the Item table in our database.
    // Adding elements must be done by calling the AddItemEvent() method from any mutator that adds Items to the database.
    private readonly ReplaySubject<Item> _itemStream = new ReplaySubject<Item>(1);

    public SubItem(){}

    // Adds a given element to a ReplaySubject<Item> object and notifies all subscribers to that sequence.
    // Call this from any mutator that adds Items to the database.
    public Item AddItemEvent(Item item)
    {
        _itemStream.OnNext(item);
        return item;
    }

    // Return this from a subscription method.
    public IObservable<Item> Items()
    {
        return _itemStream.AsObservable();
    }
}
```
For reference, my Mutators and Subscribers look like this:
```
using GraphQL.Subscription;
using GraphQL.Types;

public class Subscription 
{
    [GraphQLMetadata(Name = "itemAdded", Type = ResolverType.Subscriber)]
    public IObservable<Item> SubscribeItemAdded(ResolveEventStreamContext context)
    { return MySingletons.SubItems.Items(); }

    [GraphQLMetadata(Name = "itemAdded")]
    public Item ResolveItem(ResolveFieldContext context)
    { return = context.Source as Item; }
}
```
```
public class Mutation
{
    [GraphQLMetadata("addItem")]
    public Item Add(string name) 
    {
        // create and add item to my database
        MySingletons.SubItems.AddItemEvent(item);
        return item;
    }
}
```
And some important bits from my Startup.cs file:
```
public void ConfigureServices(IServiceCollection services)
{
    services
        //.AddSingleton<SubItem>() // I can't tell what this does. Nothing seems to break on commenting this
        .AddSingleton<SchemaTypes>() // SchemaTypes inherits from GraphQL.Types.Schema
        .AddGraphQL()
        .AddWebSockets()
        .AddDataLoader();
        //.AddGraphTypes(typeof(SchemaTypes)); // Don't know what this does but it doesn't seem to be needed
}

public void Configure(IApplicationBuilder app)
{
    /// Unimportant things

    app.UseWebSockets();

    // These two need an arguments of type ISchema to work
    app.UseGraphQLWebSockets<SchemaTypes>("/graphql"); 
    app.UseGraphQL<SchemaTypes>("/graphql");

    app.UseGraphiQLServer(new GraphiQLOptions
    {
        Path = "/ui/graphiql",
        GraphQLEndPoint = "/graphql",
    });
}
```

So if I understand how things are working, in order for EntityGraphQL to handle graphql subscriptions, it needs to do what 
`app.UseGraphQLWebSockets<SchemaTypes>("/graphql");`
is doing, and also needs to handle subscription methods similar to how it already handles mutation methods?

**Comment by lukemurray** [comment]
I'm a little confused. It looks like you are using https://github.com/graphql-dotnet/ I'm unsure how you are using EntityGraphQL and if you are, why are you trying to use 2 different GraphQL libraries?

**Comment by patty-caked** [comment]
> I'm a little confused. It looks like you are using https://github.com/graphql-dotnet/ I'm unsure how you are using EntityGraphQL and if you are, why are you trying to use 2 different GraphQL libraries?

I have two projects I'm working with.
One of them uses graphql-dotnet, and is used to help me learn GraphQL concepts in an easier to understand environment.
The other uses EntityGraphQL, and is where I plan on implementing new features after I've explored them in the other project.
