### ISSUE TITLE
Update list through mutations

### ISSUE THREAD

**Issue by pierrebelin** [EntityGraphQL/EntityGraphQL#92]
Hello !

I have an issue with updating lists through mutations. I clearly missed something, but I'm struggling since 2 days, and I can't find out how to deal with it.

I have a class including a list of the other class.

```
[MutationArguments]
public class UserGroupCreateArgs 
{
    [Required(AllowEmptyStrings = false, ErrorMessage = "Display name is required")]
    public string DisplayName { get; set; }
    public List<UserNotificationGroupSlotArg> Slots { get; set; }
}

public class UserNotificationGroupSlotArg
{
    public string Name { get; set; }
}
```

And I declare the mutation function with this class.

```   
public class UserMutations()
{
        public Expression<Func<DbContext, UserNotificationGroup>> CreateUserNotificationGroup(DbContext db, UserGroupCreateArgs args)
        {
        }
}
``` 

Then, I'm adding the entire class to the InputType. Both classes are created only for input, and I didn't add it before (that why I added "Args" in the class' name).

```
var schemaProvider = GraphQLSchemaCreator.CreateSchema<AppDataDbContext>();
schemaProvider.AddInputType<UserGroupCreateArgs>("UserGroupCreateArgs", "UserGroupCreateArgs").AddAllFields(true);

schemaProvider.AddMutationFrom(new UserMutations());
var query = "mutation { createUserNotificationGroup(displayName: \"Test4\", enabled: true, callOut: true, slots:[{ name: \"test\"}]) { id } }";
var result = schemaProvider.ExecuteRequest(new QueryRequest() { Query = query }, dbContext, _serviceProvider, null);
```

It returns this error: No schema type found for dotnet type List`1. Make sure you add it or add a type mapping

I tried to use ICollection or IList, it returns that it cannot use interfaces.
I tried to add `List<UserNotificationGroupSlotArg>` as InputType, but it does not recognize the property `name`.

I really missed something there, isn't it ?

**Comment by lukemurray** [comment]
Hi there,

You are doing it correctly! You hit a bug in the processing of List arguments. Thanks for finding it. v1.1.1 fixes it and will be published shortly.

**Comment by pierrebelin** [comment]
Hi Luke

Thanks for your answer, I was going crazy! 
I can't wait the v1.1.1 then.
