### ISSUE TITLE
NotSupportedException error when using EntityGraphQL.AspNet.MapGraphQL with .Net 5

### ISSUE THREAD

**Issue by sim8500** [EntityGraphQL/EntityGraphQL#99]
I'm trying to run a sandbox Web API in .Net 5 with some simple DbContext and following dependencies:

- EntityGraphQL Version="1.2.0"
- EntityGraphQL.AspNetnVersion="1.2.0"
- Microsoft.EntityFrameworkCore Version="5.0.14"
- Microsoft.EntityFrameworkCore.Design Version="5.0.14" 
-  Microsoft.EntityFrameworkCore.InMemory Version="5.0.14"

    
   After following the Quick Start tutorial and sending POST request to /graphql endpoint I see following error in the console (analogous error occurs when running with IIS Express):
   

>     System.NotSupportedException: Specified method is not supported.
>          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.get_Length()
>          at EntityGraphQL.AspNet.EntityGraphQLEndpointRouteExtensions.<>c__DisplayClass0_0`1.<<MapGraphQL>b__0>d.MoveNext()
>       --- End of stack trace from previous location ---

**Comment by lukemurray** [comment]
Thanks. See 1.2.1

**Comment by sim8500** [comment]
It works now, thank you 🙏
